/***************************************************************************************************
 * Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/

#include <algorithm>
#include <iostream>
#include <optional>
#include <string>
#include <vector>

#include "cutegen/cutegen_base_dynamic.hpp"
#include "cutegen/swizzle.hpp"

#include "gtest/gtest.h"

#include "utils.hpp"

namespace cg = cutegen;

TEST(SwizzleTest, FromString)
{
    // Test swizzle parsing
    {
        auto optSwizzleA = cg::from_string<cg::swizzle>(std::string("S<1,0,2>"));
        EXPECT_TRUE(optSwizzleA.has_value());
        EXPECT_EQ(cg::swizzle(1, 0, 2), optSwizzleA.value());
        auto optSwizzleB = cg::from_string<cg::swizzle>(std::string("S <2, 0, -3 >"));
        EXPECT_TRUE(optSwizzleB.has_value());
        EXPECT_EQ(cg::swizzle(2, 0, -3), optSwizzleB.value());
    }
    // Test invalid swizzle strings
    {
        // Num bits can't be negative
        auto optSwizzleC = cg::from_string<cg::swizzle>(std::string("S<-1,0,2>"));
        EXPECT_FALSE(optSwizzleC.has_value());
        // Not enough values
        auto optSwizzleD = cg::from_string<cg::swizzle>(std::string("S<2,0>"));
        EXPECT_FALSE(optSwizzleD.has_value());
        // Invalid combination of values (num bits greater than num shift)
        auto optSwizzleE = cg::from_string<cg::swizzle>(std::string("S<4,0,2>"));
        EXPECT_FALSE(optSwizzleE.has_value());
        // Invalid combination of values (sum larger than swizzle bitwidth)
        auto optSwizzleF = cg::from_string<cg::swizzle>(std::string("S<16,12,5>"));
        EXPECT_FALSE(optSwizzleF.has_value());
    }
}

TEST(SwizzleTest, Codec)
{
    EXPECT_TRUE(test_codec(cg::swizzle(1, 0, 2)));
    EXPECT_TRUE(test_codec(cg::swizzle(2, 0, -3)));
    // Verify failure on invalid buffers
    {
        std::vector<char> buffer;
        cg::encode(buffer, cg::swizzle(1, 0, 2));
        buffer.resize(buffer.size() - 1);
        auto dec = cg::decode<cg::swizzle>(buffer);
        EXPECT_FALSE(dec.has_value());
    }
}

TEST(SwizzleTest, Apply)
{
    using int_tuple = cg::int_tuple;
    // (Tests below use result outputs generated by CuTe C++)
    cg::swizzle sw333(3, 3, 3);
    // input: 0xDEADBEEF
    // input: 11011110101011011011111011101111
    // mask :                        111
    //    & :                        011
    // shift:                        -->011
    //   xor:  (with input)             110
    //output: 11011110101011011011111011110111
    //output: 0xDEADBEF7
    EXPECT_EQ(0xDEADBEF7, sw333(cg::int_tuple(0xDEADBEEF)));
    EXPECT_TRUE(holds_dynamic_int(sw333(cg::int_tuple(cg::dynamic_t{}))));
    cg::swizzle sw334(3, 3, 4);
    EXPECT_EQ(sw334(int_tuple(0x12345678)), 0x12345658);
    cg::swizzle sw012(0, 1, 2);
    EXPECT_EQ(sw012(int_tuple(0xFAE0DBCB)), 0xFAE0DBCB);
    // input: 0x2468134F
    // input: 100100011010000001001101001111
    // mask :                             11
    //    & :                             11
    // shift:                          11<-- (-3)
    //   xor:  (with input)            10
    //output: 100100011010000001001101010111
    //output: 0x24681357
    cg::swizzle sw20_3(2, 0, -3);
    EXPECT_EQ(sw20_3(int_tuple(0x2468134FU)), 0x24681357U);
    cg::swizzle sw44_11(4, 4, -11);
    EXPECT_EQ(sw44_11(int_tuple(0x24681357U)), 0x246A9357U);
}

TEST(SwizzleTest, MaxAlignment)
{
    // max alignment return generalized alignment as (1 << M)
    cg::swizzle sw343(3, 4, 3);
    EXPECT_EQ(16, cg::max_alignment(sw343));
    cg::swizzle sw012(0, 1, 2);
    EXPECT_EQ(2, cg::max_alignment(sw012));
    cg::swizzle sw25_3(2, 5, -3);
    EXPECT_EQ(32, cg::max_alignment(sw25_3));
}

TEST(SwizzleTest, Recast)
{
    cg::swizzle sw343(3, 4, 3);
    {
        cg::swizzle sw323 = cg::upcast(4, sw343);
        EXPECT_EQ(cg::swizzle(3, 2, 3), sw323);
    }
    {
        cg::swizzle sw363 = cg::downcast(4, sw343);
        EXPECT_EQ(cg::swizzle(3, 6, 3), sw363);
    }
}
