/***************************************************************************************************
 * Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/

#include <iostream>

#include "cutlass/cutlass.h"
#include "cute/tensor.hpp"
#include "cute/atom/mma_atom.hpp"

#include "cutlass/numeric_types.h"

#include "cutlass/gemm/device/gemm_universal_adapter.h"
#include "cutlass/gemm/kernel/gemm_universal.hpp"
#include "cutlass/gemm/collective/collective_builder.hpp"

#include "cutlass/epilogue/dispatch_policy.hpp"
#include "cutlass/epilogue/collective/collective_builder.hpp"

#include "../../../common/cutlass_unit_test.h"
#include "../gemm_testbed_3x.hpp"

using namespace cute;

#if defined(CUTLASS_ARCH_MMA_SM107_SUPPORTED)

template <
  class MmaTileShape_MNK,
  class ClusterShape_MNK,
  class EpilogueSchedule,
  class MainloopSchedule,
  class ElementSFD,
  int SFDVectorSize
>
void test_sm107_nvf4_nvf4_f16_nvf4() {
  using ElementA           = cute::tuple<cutlass::float_e2m1_t, cutlass::float_ue5m3_t>;
  using GmemLayoutA        = cutlass::layout::RowMajor;
  constexpr int AlignA     = 32;
  using ElementB           = cute::tuple<cutlass::float_e2m1_t, cutlass::float_ue5m3_t>;
  using GmemLayoutB        = cutlass::layout::ColumnMajor;
  constexpr int AlignB     = 32;
  using ElementC           = cutlass::half_t;
  using GmemLayoutC        = cutlass::layout::RowMajor;
  constexpr int AlignC     = 8;
  using ElementD           = cutlass::float_e2m1_t;
  using GmemLayoutD        = cutlass::layout::RowMajor;
  constexpr int AlignD     = 32;
  using ElementAccumulator = float;
  using ElementCompute     = float;
  // Narrow-precision D requires its own scale-factor (SFD) tensor generated by the epilogue.
  using GmemLayoutSFD      = GmemLayoutD;

  using FusionOperation = cutlass::epilogue::fusion::LinCombBlockScaleFactor<
      SFDVectorSize,
      ElementD, ElementCompute,
      ElementSFD, GmemLayoutSFD,
      ElementC
    >;

  using CollectiveEpilogue = typename cutlass::epilogue::collective::CollectiveBuilder<
      cutlass::arch::Sm107, cutlass::arch::OpClassBlockScaledTensorOp,
      MmaTileShape_MNK, ClusterShape_MNK,
      cutlass::epilogue::collective::EpilogueTileAuto,
      ElementAccumulator, ElementCompute,
      ElementC, GmemLayoutC, AlignC,
      ElementD, GmemLayoutD, AlignD,
      EpilogueSchedule,
      FusionOperation
    >::CollectiveOp;

  using CollectiveMainloop = typename cutlass::gemm::collective::CollectiveBuilder<
      cutlass::arch::Sm107, cutlass::arch::OpClassBlockScaledTensorOp,
      ElementA, GmemLayoutA, AlignA,
      ElementB, GmemLayoutB, AlignB,
      ElementAccumulator,
      MmaTileShape_MNK, ClusterShape_MNK,
      cutlass::gemm::collective::StageCountAutoCarveout<static_cast<int>(sizeof(typename CollectiveEpilogue::SharedStorage))>,
      MainloopSchedule
    >::CollectiveOp;

  using GemmKernel = cutlass::gemm::kernel::GemmUniversal<
      Shape<int,int,int,int>,
      CollectiveMainloop,
      CollectiveEpilogue
    >;

  using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;

  using ProblemShapeType = typename Gemm::GemmKernel::ProblemShape;
  ProblemShapeType problem_size{512, 512, 512, /* l */ 1};

  test::gemm::device::Testbed3x<Gemm> testbed;
  EXPECT_TRUE(testbed.run(problem_size));
}

// input vs16, without breuse, 1sm, output vs16, SFD = ue8m0
TEST(SM107_Device_Gemm_ue5m3xe2m1t_ue5m3xe2m1n_f16t_vs16_ue8m0xe2m1t_bstensorop_f32, 512x64x256_2x2x1_2sm_breuse) {
  test_sm107_nvf4_nvf4_f16_nvf4<Shape<_512,_64,_256>, Shape<_2,_2,_1>,
      cutlass::epilogue::TmaWarpSpecialized2Sm,
      cutlass::gemm::KernelTmaWarpSpecialized2SmSm107BlockScaledMxNvf4Vs16WithBreuse,
      cutlass::float_ue8m0_t, 16>();
}

// input vs32, with breuse, 1sm, output vs16, SFD = ue4m3
TEST(SM107_Device_Gemm_ue5m3xe2m1t_ue5m3xe2m1n_f16t_vs16_ue4m3xe2m1t_bstensorop_f32, 256x128x256_2x2x1_1sm_breuse) {
  test_sm107_nvf4_nvf4_f16_nvf4<Shape<_256,_128,_256>, Shape<_2,_2,_1>,
      cutlass::epilogue::TmaWarpSpecialized1Sm,
      cutlass::gemm::KernelTmaWarpSpecialized1SmSm107BlockScaledMxNvf4Vs32WithBreuse,
      cutlass::float_ue4m3_t, 16>();
}

// input vs16, without breuse, 2sm, output vs16, SFD = ue5m3
TEST(SM107_Device_Gemm_ue5m3xe2m1t_ue5m3xe2m1n_f16t_vs16_ue5m3xe2m1t_bstensorop_f32, 256x64x256_2x2x1_2sm) {
  test_sm107_nvf4_nvf4_f16_nvf4<Shape<_256,_64,_256>, Shape<_2,_2,_1>,
      cutlass::epilogue::TmaWarpSpecialized2Sm,
      cutlass::gemm::KernelTmaWarpSpecialized2SmSm107BlockScaledMxNvf4Vs16WithoutBreuse,
      cutlass::float_ue5m3_t, 16>();
}

// input vs32, without breuse, 1sm, output vs32, SFD = ue8m0
TEST(SM107_Device_Gemm_ue5m3xe2m1t_ue5m3xe2m1n_f16t_vs32_ue8m0xe2m1t_bstensorop_f32, 128x128x256_2x2x1_1sm) {
  test_sm107_nvf4_nvf4_f16_nvf4<Shape<_128,_128,_256>, Shape<_2,_2,_1>,
      cutlass::epilogue::TmaWarpSpecialized1Sm,
      cutlass::gemm::KernelTmaWarpSpecialized1SmSm107BlockScaledMxNvf4Vs32WithoutBreuse,
      cutlass::float_ue8m0_t, 32>();
}

// input vs16, without breuse, 2sm, output vs32, SFD = ue4m3
TEST(SM107_Device_Gemm_ue5m3xe2m1t_ue5m3xe2m1n_f16t_vs32_ue4m3xe2m1t_bstensorop_f32, 256x256x256_2x2x1_2sm) {
  test_sm107_nvf4_nvf4_f16_nvf4<Shape<_256,_256,_256>, Shape<_2,_2,_1>,
      cutlass::epilogue::TmaWarpSpecialized2Sm,
      cutlass::gemm::KernelTmaWarpSpecialized2SmSm107BlockScaledMxNvf4Vs16WithoutBreuse,
      cutlass::float_ue4m3_t, 32>();
}

// input vs32, with breuse, 2sm, output vs32, SFD = ue5m3
TEST(SM107_Device_Gemm_ue5m3xe2m1t_ue5m3xe2m1n_f16t_vs32_ue5m3xe2m1t_bstensorop_f32, 512x256x256_2x2x1_2sm_breuse) {
  test_sm107_nvf4_nvf4_f16_nvf4<Shape<_512,_256,_256>, Shape<_2,_2,_1>,
      cutlass::epilogue::TmaWarpSpecialized2Sm,
      cutlass::gemm::KernelTmaWarpSpecialized2SmSm107BlockScaledMxNvf4Vs32WithBreuse,
      cutlass::float_ue5m3_t, 32>();
}

#endif
