# SPDX-FileCopyrightText: Copyright (c) 2025 - 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# Use of this software is governed by the terms and conditions of the
# NVIDIA End User License Agreement (EULA), available at:
# https://docs.nvidia.com/cutlass/latest/media/docs/pythonDSL/license.html
#
# Any use, reproduction, disclosure, or distribution of this software
# and related documentation outside the scope permitted by the EULA
# is strictly prohibited.

"""
This module provides helper functions that are generated by the preprocessor.
The preprocessor read through python's ast and changes the input code.
"""

from collections.abc import Callable, Iterator
from dataclasses import dataclass
from typing import Any, overload
from typing_extensions import deprecated
import warnings
import inspect
import types
from types import BuiltinFunctionType
from functools import lru_cache
from inspect import getmembers
import builtins

from .utils.logger import log
from .common import *

from ._mlir_helpers.arith import ArithValue


class Executor:
    """
    The Executor class handles dynamic and compile-time (constexpr) execution
    of "for" loops and "if-else-elif" statements.

    Methods:
        set_functions:  Assigns the functions for checking loop bounds and
                        conditional evaluation.

        for_execute: Generates MLIR for OP
        while_execute: Generates MLIR while OP
        if_execute: generate MLIR if OP
    """

    def __init__(self) -> None:
        self._is_dynamic_expression: Callable[..., Any] | None = None
        self._loop_execute_range_dynamic: Callable[..., Any] | None = None
        self._if_dynamic: Callable[..., Any] | None = None
        self._while_dynamic: Callable[..., Any] | None = None
        self._compare_executor: Callable[..., Any] | None = None
        self._builtin_redirector: Callable[..., Any] | None = None
        self._ifexp_dynamic: Callable[..., Any] | None = None

    @staticmethod
    def _default_builtin_redirector(fcn: Callable[..., Any]) -> Callable[..., Any]:
        # Default to no redirect
        return fcn

    def set_functions(
        self,
        *,
        is_dynamic_expression: Callable[..., Any],
        loop_execute_range_dynamic: Callable[..., Any],
        if_dynamic: Callable[..., Any],
        while_dynamic: Callable[..., Any],
        compare_executor: Callable[..., Any],
        builtin_redirector: Callable[..., Any] = _default_builtin_redirector,
        ifexp_dynamic: Callable[..., Any] | None = None,
    ) -> None:
        self._is_dynamic_expression = is_dynamic_expression
        self._loop_execute_range_dynamic = loop_execute_range_dynamic
        self._if_dynamic = if_dynamic
        self._while_dynamic = while_dynamic
        self._compare_executor = compare_executor
        self._builtin_redirector = builtin_redirector
        self._ifexp_dynamic = ifexp_dynamic

    @staticmethod
    def convert_to_list(x: Any) -> list[Any]:
        """This function is used to convert x to a list.
        If x is None, return an empty list.
        If x is not a list, return a list containing x.
        Otherwise, return x itself.
        """
        if x is None:
            return []
        if not isinstance(x, list):
            return [x]
        return x

    @staticmethod
    def converge_ret_val(res: Any) -> Any:
        """This function is used to converge res (the return value) of the function.
        If res is None, return None.
        If res is a list and has only one element, return the element.
        Otherwise, return res itself.
        """
        if res is None:
            return res
        elif isinstance(res, list) and len(res) == 1:
            return res[0]
        return res

    def for_execute(
        self,
        func: Callable[..., Any],
        start: Any,
        stop: Any,
        step: Any,
        write_args: list[Any] = [],
        full_write_args_count: int = 0,
        write_args_names: list[str] = [],
        unroll: int = -1,
        unroll_full: bool = False,
        prefetch_stages: int | None = None,
        vectorize: int | None = None,
        at_least_once: bool = False,
    ) -> Any:
        assert self._loop_execute_range_dynamic, (
            "Functions must be set before execution."
        )
        log().debug("start [%s] stop [%s] step [%s]", start, stop, step)

        return self._loop_execute_range_dynamic(
            func,
            start,
            stop,
            step,
            write_args=write_args,
            full_write_args_count=full_write_args_count,
            write_args_names=write_args_names,
            unroll=unroll,
            unroll_full=unroll_full,
            prefetch_stages=prefetch_stages,
            vectorize=vectorize,
            at_least_once=at_least_once,
        )

    def if_execute(
        self,
        pred: Any,
        then_block: Callable[..., Any],
        else_block: Callable[..., Any] | None = None,
        write_args: list[Any] = [],
        full_write_args_count: int = 0,
        write_args_names: list[str] = [],
    ) -> Any:
        assert self._if_dynamic, "Functions must be set before execution."

        # MLIR generation
        return self._if_dynamic(
            pred,
            then_block,
            else_block,
            write_args,
            full_write_args_count,
            write_args_names,
        )

    def while_execute(
        self,
        while_before_block: Callable[..., Any],
        while_after_block: Callable[..., Any],
        write_args: list[Any] = [],
        full_write_args_count: int = 0,
        write_args_names: list[str] = [],
    ) -> Any:
        assert self._while_dynamic, "Functions must be set before execution."

        # MLIR generation
        return self._while_dynamic(
            while_before_block,
            while_after_block,
            write_args,
            full_write_args_count,
            write_args_names,
        )

    def ifexp_execute(
        self,
        pred: Any,
        block_args: tuple[Any, ...],
        then_block: Callable[..., Any],
        else_block: Callable[..., Any],
    ) -> Any:
        assert self._ifexp_dynamic, "Functions must be set before execution."
        return self._ifexp_dynamic(pred, block_args, then_block, else_block)


# =============================================================================
# Decorator
# =============================================================================

executor = Executor()


def loop_selector(
    start: Any,
    stop: Any,
    step: Any,
    *,
    write_args: list[Any] = [],
    full_write_args_count: int = 0,
    write_args_names: list[str] = [],
    unroll: int = -1,
    unroll_full: bool = False,
    prefetch_stages: int | None = None,
    vectorize: int | None = None,
    at_least_once: bool = False,
) -> Callable[..., Any]:
    log().debug(
        "start [%s] stop [%s] step [%s] write_args [%s] full_write_args_count [%s] write_args_names [%s] unroll [%s] unroll_full [%s] prefetch_stages [%s] vectorize [%s] at_least_once [%s]",
        start,
        stop,
        step,
        write_args,
        full_write_args_count,
        write_args_names,
        unroll,
        unroll_full,
        prefetch_stages,
        vectorize,
        at_least_once,
    )
    from .typing import Integer, Numeric

    def _maybe_upcast(value: Any) -> Any:
        if isinstance(value, Integer):
            value = value.ir_value()

        return value

    start = _maybe_upcast(start)
    stop = _maybe_upcast(stop)
    step = _maybe_upcast(step)

    def ir_loop(func: Callable[..., Any]) -> Any:
        return executor.for_execute(
            func,
            start,
            stop,
            step,
            write_args=write_args,
            full_write_args_count=full_write_args_count,
            write_args_names=write_args_names,
            unroll=unroll,
            unroll_full=unroll_full,
            prefetch_stages=prefetch_stages,
            vectorize=vectorize,
            at_least_once=at_least_once,
        )

    return ir_loop


def if_selector(pred: Any, write_args: list[Any] = []) -> Callable[..., Any]:
    log().debug("pred [%s] write_args [%s]", pred, write_args)
    # Handle Numeric types here?

    from .typing import Numeric

    if isinstance(pred, Numeric):
        pred = pred.value

    def ir_loop(func: Callable[..., Any]) -> Any:
        return func(pred, *write_args)

    return ir_loop


def while_selector(*, write_args: list[Any] = []) -> Callable[..., Any]:
    def ir_while_loop(func: Callable[..., Any]) -> Any:
        return func(*write_args)

    return ir_while_loop


def while_executor(
    while_before_block: Callable[..., Any],
    while_after_block: Callable[..., Any],
    write_args: list[Any] = [],
    full_write_args_count: int = 0,
    write_args_names: list[str] = [],
) -> Any:
    return executor.while_execute(
        while_before_block,
        while_after_block,
        write_args,
        full_write_args_count,
        write_args_names,
    )


def if_executor(
    pred: Any,
    then_block: Callable[..., Any],
    else_block: Callable[..., Any] | None = None,
    write_args: list[Any] = [],
    full_write_args_count: int = 0,
    write_args_names: list[str] = [],
) -> Any:
    return executor.if_execute(
        pred,
        then_block,
        else_block,
        write_args,
        full_write_args_count,
        write_args_names,
    )


def ifExp_executor(
    *,
    pred: Any,
    block_args: tuple[Any, ...],
    then_block: Callable[..., Any],
    else_block: Callable[..., Any],
) -> Any:
    if not executor._is_dynamic_expression(pred):  # type: ignore[misc]
        return then_block(*block_args) if pred else else_block(*block_args)
    else:
        return executor.ifexp_execute(pred, block_args, then_block, else_block)


# =============================================================================
# Range
# =============================================================================


class range:
    """
    A range-like object for dynamic loop iteration in the DSL.

    This class provides a range interface similar to Python's built-in range,
    but is designed to be preprocessed into constructs for dynamic
    loop execution.

    The class supports both single-argument (stop) and three-argument
    (start, stop, step) constructors with additional parameters for loop
    optimization:

    - unroll: Number of iterations to unroll (0 or 1 = no unrolling)
    - unroll_full: Whether to fully unroll the loop
    - prefetch_stages: Number of prefetch stages to generate
    - vectorize: Whether to vectorize the loop (default: None)
    - at_least_once: Annotate the loop as executing at least one iteration,
      suppressing the zero-iteration bypass edge in analyses (default: False)
    """

    @overload
    def __new__(
        cls,
        stop: Any,
        unroll: int = 0,
        unroll_full: bool = False,
        prefetch_stages: int | None = None,
        vectorize: int | None = None,
        at_least_once: bool = False,
    ) -> "range": ...

    @overload
    def __new__(
        cls,
        start: Any,
        stop: Any,
        step: Any,
        unroll: int = 0,
        unroll_full: bool = False,
        prefetch_stages: int | None = None,
        vectorize: int | None = None,
        at_least_once: bool = False,
    ) -> "range": ...

    def __new__(cls, *args: Any, **kwargs: Any) -> "range":
        raise DSLRuntimeError("dynamic range should be always preprocessed to IR")

    def __iter__(self) -> Iterator[int]:
        raise DSLRuntimeError("dynamic range should be always preprocessed to IR")


@deprecated(
    "range_dynamic is deprecated and will be removed in the future, please remove it."
)
def range_dynamic(*args: Any, **kwargs: Any) -> None:
    raise DSLRuntimeError("range_dynamic should be always preprocessed to IR")


def range_constexpr(*args: Any) -> None:
    raise DSLRuntimeError("range_constexpr should be preprocessed by preprocessor.")


# =============================================================================
# If expressions
# =============================================================================


def const_expr(expression: Any) -> Any:
    """
    This function is used to check if the expression is a python value.
    If the expression is a python value, return the boolean value of the expression.
    If the expression is a dynamic expression, raise an error.
    """
    from .typing import Numeric

    failed = False

    if isinstance(expression, Numeric):
        if isinstance(expression.value, (int, float, bool)):
            return expression.value
        else:
            failed = True
    elif executor._is_dynamic_expression(expression):  # type: ignore[misc]
        failed = True

    if failed:
        raise DSLRuntimeError(
            f"The function `const_expr({expression})` received a dynamic expression (non compile-time constant).",
            context={
                "If your expression depends on dynamic values": "Remove `const_expr()`",
            },
        )
    return expression


@deprecated(
    "dynamic_expr is deprecated and will be removed in the future, please remove it."
)
def dynamic_expr(expression: Any) -> Any:
    return expression


# =============================================================================
# Assertion & casting
# =============================================================================


def assert_executor(test: Any, msg: str | None = None) -> None:
    from .typing import Numeric

    fail = False
    # Implicit convert dynamic expression to bool is not allowed
    # So here explicitly do a None check
    if test is not None and executor._is_dynamic_expression(test):  # type: ignore[misc]
        if isinstance(test, Numeric):
            try:
                test = test.to(bool)
            except:
                fail = True
        else:
            fail = True

    if not fail:
        assert test, msg
    else:
        raise DSLRuntimeError(
            "Only constexpr (Python Value) is allowed here, but got non-constexpr (IR Values) expression.",
            suggestion="Please replace with runtime assert.",
        )


def bool_cast(value: Any) -> bool:
    if executor._is_dynamic_expression(value):  # type: ignore[misc]
        raise DSLRuntimeError(
            "Only constexpr (Python Value) is allowed here, but got non-constexpr (IR Values) expression.",
            suggestion="Please explicitly convert to boolean with expressions like comparison.",
        )
    return bool(value)


def compare_executor(left: Any, comparators: list[Any], ops: list[Any]) -> Any:
    """
    Executes comparison operations with a left operand and a list of comparators.

    Args:
        left: The leftmost value in the comparison chain
        comparators: A list of values to compare against
        ops: A list of comparison operators to apply

    Returns:
        The result of the comparison chain

    Raises:
        AssertionError: If the executor function is not set before execution
    """
    assert executor._compare_executor is not None, (
        "Function must be set before execution."
    )
    return executor._compare_executor(left, comparators, ops)


# =============================================================================
# Control flow checks
# =============================================================================
class DSLOptimizationWarning(Warning):
    """
    This warning is used to warn the user about the optimization related issues in DSL.
    """

    def __init__(self, message: str) -> None:
        self.message = message
        super().__init__()

    def __str__(self) -> str:
        return self.message


def range_value_check(*args: Any) -> tuple[int, int, int]:
    """
    Ensure all `range_constexpr` bounds are compile-time constants (Python ints).
    """
    try:
        args = tuple(arg.__index__() for arg in args)

        # Compute range size and warn if it's too large
        start = 0
        end = 0
        step = 1
        if len(args) == 1:
            end = args[0]
        elif len(args) == 2:
            start = args[0]
            end = args[1]
        elif len(args) == 3:
            start = args[0]
            end = args[1]
            step = args[2]

        range_length = (abs(end - start) - 1) // abs(step) + 1
        if range_length >= 64:
            warnings.warn(
                f"This static loop has {range_length} iterations, which may be very slow to compile, consider using `cutlass.range(..., unroll_full=True)` instead.",
                category=DSLOptimizationWarning,
                stacklevel=2,
            )

        return (start, end, step)
    except:
        raise DSLRuntimeError(
            "`range_constexpr` requires constexpr (compile-time constant) for all arguments.",
            suggestion="Use `range` instead of `range_constexpr`.",
        )


@lru_cache(maxsize=1)
def _get_self_module() -> types.ModuleType | None:
    """
    This function is used to get the owning module of this function.
    """
    return inspect.getmodule(_get_self_module)


@lru_cache(maxsize=16)
def cf_symbol_check(symbol: Any) -> None:
    """
    Check if the symbol is control flow symbol from current module.
    """

    failed = False
    name = symbol.__name__
    self_module = _get_self_module()
    if inspect.ismodule(symbol):
        if not self_module.__name__.startswith(name):  # type: ignore[union-attr]
            failed = True
    else:
        owning_module = inspect.getmodule(symbol)
        root_module = owning_module.__name__.split(".")[0]  # type: ignore[union-attr]
        self_root_module = self_module.__name__.split(".")[0]  # type: ignore[union-attr]
        if root_module != self_root_module:
            failed = True

    if failed:
        raise DSLRuntimeError(
            f"Incorrect `{name}` is used.",
            suggestion=f"Please avoid overriding `{name}` from DSL package.",
        )


def redirect_builtin_function(fcn: Any) -> Any:
    """
    This function is used to redirect built-in function call
    to the function defined in DSL package.
    """
    # Only redirect if it's a built-in
    if fcn is builtins.bool:
        return bool_cast

    if isinstance(fcn, BuiltinFunctionType):
        if fcn in [builtins.exec, builtins.eval]:
            raise DSLRuntimeError(
                f"Built-in function `{fcn.__name__}` is not supported in DSL.",
            )
        if executor._builtin_redirector:
            return executor._builtin_redirector(fcn)
    return fcn


def copy_members(dest: object, src: object) -> None:
    """
    Copies all non-callable, non-dunder members from src to dest if they exist in src.
    Skips members that are callables or have names starting with double underscores.
    """
    if id(dest) == id(src):
        return

    members = getmembers(dest)
    for name, value in members:
        if (
            name.startswith("__")
            or isinstance(value, Callable)  # type: ignore[arg-type]
            or not hasattr(src, name)
        ):
            continue
        try:
            setattr(dest, name, getattr(src, name))
        except AttributeError:
            # AttributeError means the member is no settable, like property without setter, just ignore
            pass


def get_locals_or_none(locals: dict[str, Any], symbols: list[str]) -> list[Any]:
    """
    Given a locals() dictionary and a list of symbol names, return a list of their values
    in the same order as the symbols list. If a symbol is not present in locals, None is returned
    for that symbol.
    """
    variables = []
    for symbol in symbols:
        if symbol in locals:
            variables.append(locals[symbol])
        else:
            variables.append(None)
    return variables


def closure_check(
    closures: list[Any], _visited: set[tuple[str, int]] | None = None
) -> None:
    """
    Check if the closures have any unsupported capture
    """
    if _visited is None:
        _visited = set()

    for closure in closures:
        # Use (function name, id) as identity to skip already-processed closures
        # and prevent infinite recursion with mutually-recursive captured functions
        closure_identity = (closure.__name__, id(closure))
        if closure_identity in _visited:
            continue
        _visited.add(closure_identity)

        closure_vars = inspect.getclosurevars(closure)
        for name, value in closure_vars.nonlocals.items():
            if inspect.ismodule(value):
                continue
            if inspect.isfunction(value) or inspect.ismethod(value):
                closure_check([value], _visited)
                continue
            raise DSLRuntimeError(
                f"Function `{closure.__name__}` is a closure that captures variable `{name}` and is not supported in dynamic control flow",
                suggestion="Please explicitly pass in captured variables as arguments",
            )


@dataclass
class FormattedValue:
    """
    Represents a value (from an f-string interpolation) along with its conversion and format specification.

    This is a runtime representation of ast.FormattedValue.
    See https://docs.python.org/3/library/ast.html#ast.FormattedValue

    This class is used to encapsulate a value that is to be embedded into an f-string formatted string,
    along with any conversion flags (such as '!s', '!r', or '!a') and a list of format specification strings
    (e.g., '.2f', '05d', etc).

    Attributes:
        value (Any): The value to be formatted.
        conversion (int): The ASCII code of the conversion character, defaulting to -1 (no conversion).
        format_spec (Optional[List[str]]): List of format specifier strings.
    """

    value: Any
    conversion: int = -1
    format_spec: list[str] | None = None

    def to_str(self) -> tuple[str, Any | None]:
        """
        Converts the FormattedValue into a format string component and (optional) dynamic argument.

        If the value is a dynamic expression (requires runtime evaluation), returns a printf-style placeholder and
        the corresponding dynamic value for later substitution. For static (non-dynamic) values, returns the fully
        rendered literal string and None for the dynamic value.

        Returns:
            Tuple[str, Optional[Any]]: A tuple where the first element is the format string component and the second
            element is the dynamic value (or None if not required).

        Raises:
            DSLRuntimeError: If the format spec is invalid or not supported for dynamic expressions.
        """
        if executor._is_dynamic_expression(self.value):  # type: ignore[misc]
            if self.conversion != -1:
                warnings.warn(
                    "Conversion may not be honored for dynamic expressions",
                    stacklevel=3,
                )
            if self.format_spec is not None and len(self.format_spec) > 1:
                raise DSLRuntimeError(
                    "At most one format specifier is supported for dynamic expressions",
                )
            if self.format_spec is not None:
                if self.format_spec[0].startswith(("<", ">", "^")):
                    raise DSLRuntimeError(
                        "Alignment specifier is not supported for dynamic expressions",
                    )
                return f"%{self.format_spec[0]}", self.value
            return "{}", self.value
        else:
            conversion_str = ""
            if self.conversion == 97:
                conversion_str = "!a"  # ASCII
            elif self.conversion == 114:
                conversion_str = "!r"  # repr
            elif self.conversion == 115:
                conversion_str = "!s"  # str
            if self.format_spec is not None:
                f_str = f"{{{conversion_str}:{self.format_spec[0]}}}"
            else:
                f_str = f"{{{conversion_str}}}"
            return f_str.format(self.value), None


def fstring_decompose(
    joinedStrComponent: list[str | FormattedValue],
) -> tuple[Any, ...]:
    """
    Decomposes a joined f-string component list into a format string and dynamic arguments.

    This function takes a sequence of components representing parts of an f-string,
    which may include both literal strings and FormatValue instances.
    It assembles a format string with placeholders for dynamic values
    and collects the actual dynamic argument values in order.

    Args:
        joinedStrComponent (List[Union[str, FormattedValue]]): The components of the f-string.

    Returns:
        Tuple[str, ...]: A tuple containing the format string as the first element,
                         followed by all dynamic argument values.

    Raises:
        DSLAstPreprocessorError: If an unsupported component type is encountered.
    """
    format_string = ""
    dynamic_args = []
    for component in joinedStrComponent:
        if isinstance(component, FormattedValue):
            s, v = component.to_str()
            format_string += s
            if v is not None:
                # This is a dynamic value, add to dynamic_args
                dynamic_args.append(v)
        elif isinstance(component, str):
            format_string += component
        else:
            raise DSLAstPreprocessorError(
                f"Unsupported component type in f-string: {type(component)}",
            )
    return (format_string, *dynamic_args)
