

!memref_gmem_i32_ = !cute.memref<i32, gmem, "(?):(1)">
!memref_gmem_i8_ = !cute.memref<i8, gmem, "(?):(1)">
#loc3 = loc(unknown)
module attributes {gpu.container_module} {
  gpu.module @kernels {
    func.func public @kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_True_0(%arg0: !memref_gmem_i32_ loc(unknown), %arg1: !memref_gmem_i8_ loc(unknown), %arg2: !memref_gmem_i8_ loc(unknown), %arg3: !memref_gmem_i8_ loc(unknown)) attributes {cute.kernel, gpu.kernel, nvvm.reqntid = array<i32: 32, 1, 1>} {
      %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc26)
      %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc26)
      %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc26)
      %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc26)
      %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc27)
      %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc27)
      %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc27)
      %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc27)
      %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc28)
      %0 = cute.get_shape(%lay) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
      %e0 = cute.get_leaves(%0) : !cute.shape<"(?)"> loc(#loc29)
      %itup = cute.to_int_tuple(%e0) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
      %1 = cute.get_scalars(%itup) : !cute.int_tuple<"?"> loc(#loc29)
      %2 = cute.get_stride(%lay) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
      %e0_7 = cute.get_leaves(%2) : !cute.stride<"(1)"> loc(#loc30)
      %lay_8 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc28)
      %3 = cute.get_shape(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
      %e0_9 = cute.get_leaves(%3) : !cute.shape<"(?)"> loc(#loc29)
      %itup_10 = cute.to_int_tuple(%e0_9) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
      %4 = cute.get_scalars(%itup_10) : !cute.int_tuple<"?"> loc(#loc29)
      %5 = cute.get_stride(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
      %e0_11 = cute.get_leaves(%5) : !cute.stride<"(1)"> loc(#loc30)
      %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc28)
      %6 = cute.get_shape(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
      %e0_13 = cute.get_leaves(%6) : !cute.shape<"(?)"> loc(#loc29)
      %itup_14 = cute.to_int_tuple(%e0_13) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
      %7 = cute.get_scalars(%itup_14) : !cute.int_tuple<"?"> loc(#loc29)
      %8 = cute.get_stride(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
      %e0_15 = cute.get_leaves(%8) : !cute.stride<"(1)"> loc(#loc30)
      %lay_16 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc28)
      %9 = cute.get_shape(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
      %e0_17 = cute.get_leaves(%9) : !cute.shape<"(?)"> loc(#loc29)
      %itup_18 = cute.to_int_tuple(%e0_17) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
      %10 = cute.get_scalars(%itup_18) : !cute.int_tuple<"?"> loc(#loc29)
      %11 = cute.get_stride(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
      %e0_19 = cute.get_leaves(%11) : !cute.stride<"(1)"> loc(#loc30)
      %12 = nvvm.read.ptx.sreg.tid.x : i32 loc(#loc31)
      %13 = nvvm.read.ptx.sreg.tid.y : i32 loc(#loc31)
      %14 = nvvm.read.ptx.sreg.tid.z : i32 loc(#loc31)
      %c10_i32 = arith.constant 10 : i32 loc(#loc3)
      %15 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc32)
      %c-1_i32 = arith.constant -1 : i32 loc(#loc33)
      %16 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred p;\0A\09\0A            setp.ne.b32 p, $1, 0;\0A\09\0A            vote.sync.ballot.b32 $0, p, $2;\0A\09\0A            }", "=r,r,i" %15, %c-1_i32 : (i1, i32) -> i32 loc(#loc3)
      %17 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc32)
      %c-1_i32_20 = arith.constant -1 : i32 loc(#loc34)
      %18 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.any.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %17, %c-1_i32_20 : (i1, i32) -> i1 loc(#loc3)
      %19 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc32)
      %c-1_i32_21 = arith.constant -1 : i32 loc(#loc35)
      %20 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.all.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %19, %c-1_i32_21 : (i1, i32) -> i1 loc(#loc3)
      %21 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc32)
      %c-1_i32_22 = arith.constant -1 : i32 loc(#loc36)
      %22 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.uni.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %21, %c-1_i32_22 : (i1, i32) -> i1 loc(#loc3)
      %coord = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc37)
      cute.memref.store(%arg0, %coord, %16) : (!memref_gmem_i32_, !cute.coord<"?">, i32) -> () loc(#loc37)
      %23 = arith.extui %18 : i1 to i8 loc(#loc3)
      %coord_23 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc38)
      cute.memref.store(%arg1, %coord_23, %23) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc38)
      %24 = arith.extui %20 : i1 to i8 loc(#loc3)
      %coord_24 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc39)
      cute.memref.store(%arg2, %coord_24, %24) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc39)
      %25 = arith.extui %22 : i1 to i8 loc(#loc3)
      %coord_25 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc40)
      cute.memref.store(%arg3, %coord_25, %25) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc40)
      return loc(#loc3)
    } loc(#loc25)
  } loc(#loc24)
  func.func @cutlass_vote_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_True(%arg0: !memref_gmem_i32_ loc(unknown), %arg1: !memref_gmem_i8_ loc(unknown), %arg2: !memref_gmem_i8_ loc(unknown), %arg3: !memref_gmem_i8_ loc(unknown)) attributes {llvm.emit_c_interface} {
    %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc26)
    %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc26)
    %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc26)
    %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc26)
    %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc42)
    %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc42)
    %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc42)
    %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc42)
    %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc28)
    %0 = cute.get_shape(%lay) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0 = cute.get_leaves(%0) : !cute.shape<"(?)"> loc(#loc29)
    %itup = cute.to_int_tuple(%e0) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %1 = cute.get_scalars(%itup) : !cute.int_tuple<"?"> loc(#loc29)
    %2 = cute.get_stride(%lay) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_7 = cute.get_leaves(%2) : !cute.stride<"(1)"> loc(#loc30)
    %lay_8 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc28)
    %3 = cute.get_shape(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_9 = cute.get_leaves(%3) : !cute.shape<"(?)"> loc(#loc29)
    %itup_10 = cute.to_int_tuple(%e0_9) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %4 = cute.get_scalars(%itup_10) : !cute.int_tuple<"?"> loc(#loc29)
    %5 = cute.get_stride(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_11 = cute.get_leaves(%5) : !cute.stride<"(1)"> loc(#loc30)
    %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc28)
    %6 = cute.get_shape(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_13 = cute.get_leaves(%6) : !cute.shape<"(?)"> loc(#loc29)
    %itup_14 = cute.to_int_tuple(%e0_13) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %7 = cute.get_scalars(%itup_14) : !cute.int_tuple<"?"> loc(#loc29)
    %8 = cute.get_stride(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_15 = cute.get_leaves(%8) : !cute.stride<"(1)"> loc(#loc30)
    %lay_16 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc28)
    %9 = cute.get_shape(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_17 = cute.get_leaves(%9) : !cute.shape<"(?)"> loc(#loc29)
    %itup_18 = cute.to_int_tuple(%e0_17) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %10 = cute.get_scalars(%itup_18) : !cute.int_tuple<"?"> loc(#loc29)
    %11 = cute.get_stride(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_19 = cute.get_leaves(%11) : !cute.stride<"(1)"> loc(#loc30)
    %int_tuple = cute.make_int_tuple() : () -> !cute.int_tuple<"32"> loc(#loc43)
    %sz = cute.size(%int_tuple) <{mode = [0]}> : (!cute.int_tuple<"32">) -> !cute.int_tuple<"32"> loc(#loc43)
    %e0_20 = cute.get_leaves(%sz) : !cute.int_tuple<"32"> loc(#loc43)
    %lay_21 = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc28)
    %12 = cute.get_shape(%lay_21) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_22 = cute.get_leaves(%12) : !cute.shape<"(?)"> loc(#loc29)
    %itup_23 = cute.to_int_tuple(%e0_22) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %13 = cute.get_scalars(%itup_23) : !cute.int_tuple<"?"> loc(#loc29)
    %14 = cute.get_stride(%lay_21) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_24 = cute.get_leaves(%14) : !cute.stride<"(1)"> loc(#loc30)
    %lay_25 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc28)
    %15 = cute.get_shape(%lay_25) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_26 = cute.get_leaves(%15) : !cute.shape<"(?)"> loc(#loc29)
    %itup_27 = cute.to_int_tuple(%e0_26) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %16 = cute.get_scalars(%itup_27) : !cute.int_tuple<"?"> loc(#loc29)
    %17 = cute.get_stride(%lay_25) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_28 = cute.get_leaves(%17) : !cute.stride<"(1)"> loc(#loc30)
    %lay_29 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc28)
    %18 = cute.get_shape(%lay_29) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_30 = cute.get_leaves(%18) : !cute.shape<"(?)"> loc(#loc29)
    %itup_31 = cute.to_int_tuple(%e0_30) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %19 = cute.get_scalars(%itup_31) : !cute.int_tuple<"?"> loc(#loc29)
    %20 = cute.get_stride(%lay_29) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_32 = cute.get_leaves(%20) : !cute.stride<"(1)"> loc(#loc30)
    %lay_33 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc28)
    %21 = cute.get_shape(%lay_33) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_34 = cute.get_leaves(%21) : !cute.shape<"(?)"> loc(#loc29)
    %itup_35 = cute.to_int_tuple(%e0_34) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %22 = cute.get_scalars(%itup_35) : !cute.int_tuple<"?"> loc(#loc29)
    %23 = cute.get_stride(%lay_33) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_36 = cute.get_leaves(%23) : !cute.stride<"(1)"> loc(#loc30)
    %c1 = arith.constant 1 : index loc(#loc3)
    %c32 = arith.constant 32 : index loc(#loc3)
    %c0_i32 = arith.constant 0 : i32 loc(#loc3)
    gpu.launch_func  @kernels::@kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_True_0 blocks in (%c1, %c1, %c1) threads in (%c32, %c1, %c1)  dynamic_shared_memory_size %c0_i32 args(%arg0 : !memref_gmem_i32_, %arg1 : !memref_gmem_i8_, %arg2 : !memref_gmem_i8_, %arg3 : !memref_gmem_i8_) {use_pdl = false} loc(#loc25)
    return loc(#loc44)
  } loc(#loc41)
} loc(#loc23)
#loc = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1118:42)
#loc1 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1124:61)
#loc2 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":184:6)
#loc4 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":656:19)
#loc5 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":169:15)
#loc6 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":156:66)
#loc7 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":800:29)
#loc8 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":800:54)
#loc9 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":141:17)
#loc10 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/typing.py":846:18)
#loc11 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":144:8)
#loc12 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":149:8)
#loc13 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":154:8)
#loc14 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":159:8)
#loc15 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":164:4)
#loc16 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":165:4)
#loc17 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":166:4)
#loc18 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":167:4)
#loc19 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1127:57)
#loc20 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/runtime.py":358:15)
#loc21 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":186:15)
#loc22 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1138:46)
#loc23 = loc("module = ir.Module.create(loc=self.get_location(frame))"(#loc))
#loc24 = loc("self._build_gpu_module(gpu_module_attrs, loc=self.get_location(frame))"(#loc1))
#loc25 = loc(").launch("(#loc2))
#loc26 = loc("fop_args = list(fop.regions[0].blocks[0].arguments)"(#loc4))
#loc27 = loc("return _Tensor("(#loc5))
#loc28 = loc("return f\22tensor<{pretty_str(self.iterator)} o {pretty_str(self.layout)}>\22"(#loc6))
#loc29 = loc("return f\22{pretty_str(self.shape)}:{pretty_str(self.stride)}\22"(#loc7))
#loc30 = loc("return f\22{pretty_str(self.shape)}:{pretty_str(self.stride)}\22"(#loc8))
#loc31 = loc("tidx, _, _ = cute.arch.thread_idx()"(#loc9))
#loc32 = loc("res_val = op(lhs_val, rhs_val)"(#loc10))
#loc33 = loc("ptx_vote_ballot_sync(tidx < 10)"(#loc11))
#loc34 = loc("ptx_vote_any_sync(tidx < 10)"(#loc12))
#loc35 = loc("ptx_vote_all_sync(tidx < 10)"(#loc13))
#loc36 = loc("ptx_vote_uni_sync(tidx < 10)"(#loc14))
#loc37 = loc("mBallot[tidx] = vote_ballot"(#loc15))
#loc38 = loc("mAny[tidx] = vote_any"(#loc16))
#loc39 = loc("mAll[tidx] = vote_all"(#loc17))
#loc40 = loc("mUni[tidx] = vote_uni"(#loc18))
#loc41 = loc("function_name, (func_types, []), loc=self.get_location(frame)"(#loc19))
#loc42 = loc("return CoreTensor(values[0].value, self._dtype)"(#loc20))
#loc43 = loc("block=[cute.size(WARP_SIZE, mode=[0]), 1, 1],"(#loc21))
#loc44 = loc("func.ReturnOp([], loc=self.get_location(frame))"(#loc22))



!memref_gmem_i32_ = !cute.memref<i32, gmem, "(?):(1)">
!memref_gmem_i8_ = !cute.memref<i8, gmem, "(?):(1)">
#loc3 = loc(unknown)
module attributes {gpu.container_module} {
  gpu.module @kernels {
    func.func public @kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_False_0(%arg0: !memref_gmem_i32_ loc(unknown), %arg1: !memref_gmem_i8_ loc(unknown), %arg2: !memref_gmem_i8_ loc(unknown), %arg3: !memref_gmem_i8_ loc(unknown)) attributes {cute.kernel, gpu.kernel, nvvm.reqntid = array<i32: 32, 1, 1>} {
      %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc26)
      %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc26)
      %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc26)
      %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc26)
      %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc27)
      %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc27)
      %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc27)
      %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc27)
      %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc28)
      %0 = cute.get_shape(%lay) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
      %e0 = cute.get_leaves(%0) : !cute.shape<"(?)"> loc(#loc29)
      %itup = cute.to_int_tuple(%e0) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
      %1 = cute.get_scalars(%itup) : !cute.int_tuple<"?"> loc(#loc29)
      %2 = cute.get_stride(%lay) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
      %e0_7 = cute.get_leaves(%2) : !cute.stride<"(1)"> loc(#loc30)
      %lay_8 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc28)
      %3 = cute.get_shape(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
      %e0_9 = cute.get_leaves(%3) : !cute.shape<"(?)"> loc(#loc29)
      %itup_10 = cute.to_int_tuple(%e0_9) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
      %4 = cute.get_scalars(%itup_10) : !cute.int_tuple<"?"> loc(#loc29)
      %5 = cute.get_stride(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
      %e0_11 = cute.get_leaves(%5) : !cute.stride<"(1)"> loc(#loc30)
      %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc28)
      %6 = cute.get_shape(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
      %e0_13 = cute.get_leaves(%6) : !cute.shape<"(?)"> loc(#loc29)
      %itup_14 = cute.to_int_tuple(%e0_13) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
      %7 = cute.get_scalars(%itup_14) : !cute.int_tuple<"?"> loc(#loc29)
      %8 = cute.get_stride(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
      %e0_15 = cute.get_leaves(%8) : !cute.stride<"(1)"> loc(#loc30)
      %lay_16 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc28)
      %9 = cute.get_shape(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
      %e0_17 = cute.get_leaves(%9) : !cute.shape<"(?)"> loc(#loc29)
      %itup_18 = cute.to_int_tuple(%e0_17) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
      %10 = cute.get_scalars(%itup_18) : !cute.int_tuple<"?"> loc(#loc29)
      %11 = cute.get_stride(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
      %e0_19 = cute.get_leaves(%11) : !cute.stride<"(1)"> loc(#loc30)
      %12 = nvvm.read.ptx.sreg.tid.x : i32 loc(#loc31)
      %13 = nvvm.read.ptx.sreg.tid.y : i32 loc(#loc31)
      %14 = nvvm.read.ptx.sreg.tid.z : i32 loc(#loc31)
      %c10_i32 = arith.constant 10 : i32 loc(#loc3)
      %15 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc32)
      %c-1_i32 = arith.constant -1 : i32 loc(#loc33)
      %16 = nvvm.vote.ballot.sync %c-1_i32, %15 : i32 loc(#loc33)
      %17 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc32)
      %c-1_i32_20 = arith.constant -1 : i32 loc(#loc34)
      %18 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.any.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %17, %c-1_i32_20 : (i1, i32) -> i1 loc(#loc34)
      %19 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc32)
      %c-1_i32_21 = arith.constant -1 : i32 loc(#loc35)
      %20 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.all.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %19, %c-1_i32_21 : (i1, i32) -> i1 loc(#loc35)
      %21 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc32)
      %c-1_i32_22 = arith.constant -1 : i32 loc(#loc36)
      %22 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.uni.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %21, %c-1_i32_22 : (i1, i32) -> i1 loc(#loc36)
      %coord = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc37)
      cute.memref.store(%arg0, %coord, %16) : (!memref_gmem_i32_, !cute.coord<"?">, i32) -> () loc(#loc37)
      %23 = arith.extui %18 : i1 to i8 loc(#loc3)
      %coord_23 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc38)
      cute.memref.store(%arg1, %coord_23, %23) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc38)
      %24 = arith.extui %20 : i1 to i8 loc(#loc3)
      %coord_24 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc39)
      cute.memref.store(%arg2, %coord_24, %24) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc39)
      %25 = arith.extui %22 : i1 to i8 loc(#loc3)
      %coord_25 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc40)
      cute.memref.store(%arg3, %coord_25, %25) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc40)
      return loc(#loc3)
    } loc(#loc25)
  } loc(#loc24)
  func.func @cutlass_vote_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_False(%arg0: !memref_gmem_i32_ loc(unknown), %arg1: !memref_gmem_i8_ loc(unknown), %arg2: !memref_gmem_i8_ loc(unknown), %arg3: !memref_gmem_i8_ loc(unknown)) attributes {llvm.emit_c_interface} {
    %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc26)
    %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc26)
    %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc26)
    %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc26)
    %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc42)
    %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc42)
    %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc42)
    %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc42)
    %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc28)
    %0 = cute.get_shape(%lay) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0 = cute.get_leaves(%0) : !cute.shape<"(?)"> loc(#loc29)
    %itup = cute.to_int_tuple(%e0) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %1 = cute.get_scalars(%itup) : !cute.int_tuple<"?"> loc(#loc29)
    %2 = cute.get_stride(%lay) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_7 = cute.get_leaves(%2) : !cute.stride<"(1)"> loc(#loc30)
    %lay_8 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc28)
    %3 = cute.get_shape(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_9 = cute.get_leaves(%3) : !cute.shape<"(?)"> loc(#loc29)
    %itup_10 = cute.to_int_tuple(%e0_9) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %4 = cute.get_scalars(%itup_10) : !cute.int_tuple<"?"> loc(#loc29)
    %5 = cute.get_stride(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_11 = cute.get_leaves(%5) : !cute.stride<"(1)"> loc(#loc30)
    %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc28)
    %6 = cute.get_shape(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_13 = cute.get_leaves(%6) : !cute.shape<"(?)"> loc(#loc29)
    %itup_14 = cute.to_int_tuple(%e0_13) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %7 = cute.get_scalars(%itup_14) : !cute.int_tuple<"?"> loc(#loc29)
    %8 = cute.get_stride(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_15 = cute.get_leaves(%8) : !cute.stride<"(1)"> loc(#loc30)
    %lay_16 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc28)
    %9 = cute.get_shape(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_17 = cute.get_leaves(%9) : !cute.shape<"(?)"> loc(#loc29)
    %itup_18 = cute.to_int_tuple(%e0_17) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %10 = cute.get_scalars(%itup_18) : !cute.int_tuple<"?"> loc(#loc29)
    %11 = cute.get_stride(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_19 = cute.get_leaves(%11) : !cute.stride<"(1)"> loc(#loc30)
    %int_tuple = cute.make_int_tuple() : () -> !cute.int_tuple<"32"> loc(#loc43)
    %sz = cute.size(%int_tuple) <{mode = [0]}> : (!cute.int_tuple<"32">) -> !cute.int_tuple<"32"> loc(#loc43)
    %e0_20 = cute.get_leaves(%sz) : !cute.int_tuple<"32"> loc(#loc43)
    %lay_21 = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc28)
    %12 = cute.get_shape(%lay_21) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_22 = cute.get_leaves(%12) : !cute.shape<"(?)"> loc(#loc29)
    %itup_23 = cute.to_int_tuple(%e0_22) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %13 = cute.get_scalars(%itup_23) : !cute.int_tuple<"?"> loc(#loc29)
    %14 = cute.get_stride(%lay_21) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_24 = cute.get_leaves(%14) : !cute.stride<"(1)"> loc(#loc30)
    %lay_25 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc28)
    %15 = cute.get_shape(%lay_25) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_26 = cute.get_leaves(%15) : !cute.shape<"(?)"> loc(#loc29)
    %itup_27 = cute.to_int_tuple(%e0_26) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %16 = cute.get_scalars(%itup_27) : !cute.int_tuple<"?"> loc(#loc29)
    %17 = cute.get_stride(%lay_25) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_28 = cute.get_leaves(%17) : !cute.stride<"(1)"> loc(#loc30)
    %lay_29 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc28)
    %18 = cute.get_shape(%lay_29) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_30 = cute.get_leaves(%18) : !cute.shape<"(?)"> loc(#loc29)
    %itup_31 = cute.to_int_tuple(%e0_30) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %19 = cute.get_scalars(%itup_31) : !cute.int_tuple<"?"> loc(#loc29)
    %20 = cute.get_stride(%lay_29) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_32 = cute.get_leaves(%20) : !cute.stride<"(1)"> loc(#loc30)
    %lay_33 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc28)
    %21 = cute.get_shape(%lay_33) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc29)
    %e0_34 = cute.get_leaves(%21) : !cute.shape<"(?)"> loc(#loc29)
    %itup_35 = cute.to_int_tuple(%e0_34) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc29)
    %22 = cute.get_scalars(%itup_35) : !cute.int_tuple<"?"> loc(#loc29)
    %23 = cute.get_stride(%lay_33) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc30)
    %e0_36 = cute.get_leaves(%23) : !cute.stride<"(1)"> loc(#loc30)
    %c1 = arith.constant 1 : index loc(#loc3)
    %c32 = arith.constant 32 : index loc(#loc3)
    %c0_i32 = arith.constant 0 : i32 loc(#loc3)
    gpu.launch_func  @kernels::@kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_False_0 blocks in (%c1, %c1, %c1) threads in (%c32, %c1, %c1)  dynamic_shared_memory_size %c0_i32 args(%arg0 : !memref_gmem_i32_, %arg1 : !memref_gmem_i8_, %arg2 : !memref_gmem_i8_, %arg3 : !memref_gmem_i8_) {use_pdl = false} loc(#loc25)
    return loc(#loc44)
  } loc(#loc41)
} loc(#loc23)
#loc = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1118:42)
#loc1 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1124:61)
#loc2 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":184:6)
#loc4 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":656:19)
#loc5 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":169:15)
#loc6 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":156:66)
#loc7 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":800:29)
#loc8 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":800:54)
#loc9 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":141:17)
#loc10 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/typing.py":846:18)
#loc11 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":146:13)
#loc12 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":151:13)
#loc13 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":156:13)
#loc14 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":161:13)
#loc15 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":164:4)
#loc16 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":165:4)
#loc17 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":166:4)
#loc18 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":167:4)
#loc19 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1127:57)
#loc20 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/runtime.py":358:15)
#loc21 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":186:15)
#loc22 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1138:46)
#loc23 = loc("module = ir.Module.create(loc=self.get_location(frame))"(#loc))
#loc24 = loc("self._build_gpu_module(gpu_module_attrs, loc=self.get_location(frame))"(#loc1))
#loc25 = loc(").launch("(#loc2))
#loc26 = loc("fop_args = list(fop.regions[0].blocks[0].arguments)"(#loc4))
#loc27 = loc("return _Tensor("(#loc5))
#loc28 = loc("return f\22tensor<{pretty_str(self.iterator)} o {pretty_str(self.layout)}>\22"(#loc6))
#loc29 = loc("return f\22{pretty_str(self.shape)}:{pretty_str(self.stride)}\22"(#loc7))
#loc30 = loc("return f\22{pretty_str(self.shape)}:{pretty_str(self.stride)}\22"(#loc8))
#loc31 = loc("tidx, _, _ = cute.arch.thread_idx()"(#loc9))
#loc32 = loc("res_val = op(lhs_val, rhs_val)"(#loc10))
#loc33 = loc("else cute.arch.vote_ballot_sync(tidx < 10)"(#loc11))
#loc34 = loc("else cute.arch.vote_any_sync(tidx < 10)"(#loc12))
#loc35 = loc("else cute.arch.vote_all_sync(tidx < 10)"(#loc13))
#loc36 = loc("else cute.arch.vote_uni_sync(tidx < 10)"(#loc14))
#loc37 = loc("mBallot[tidx] = vote_ballot"(#loc15))
#loc38 = loc("mAny[tidx] = vote_any"(#loc16))
#loc39 = loc("mAll[tidx] = vote_all"(#loc17))
#loc40 = loc("mUni[tidx] = vote_uni"(#loc18))
#loc41 = loc("function_name, (func_types, []), loc=self.get_location(frame)"(#loc19))
#loc42 = loc("return CoreTensor(values[0].value, self._dtype)"(#loc20))
#loc43 = loc("block=[cute.size(WARP_SIZE, mode=[0]), 1, 1],"(#loc21))
#loc44 = loc("func.ReturnOp([], loc=self.get_location(frame))"(#loc22))

