

!memref_gmem_i32_ = !cute.memref<i32, gmem, "(?):(1)">
!memref_gmem_i8_ = !cute.memref<i8, gmem, "(?):(1)">
#loc = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":174:0)
#loc1 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":137:0)
#loc17 = loc("<module>"(#loc))
#loc18 = loc("<module>"(#loc1))
module attributes {gpu.container_module} {
  gpu.module @kernels {
    cuda.kernel @kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_True_0(%arg0: !memref_gmem_i32_ loc("<module>"(#loc1)), %arg1: !memref_gmem_i8_ loc("<module>"(#loc1)), %arg2: !memref_gmem_i8_ loc("<module>"(#loc1)), %arg3: !memref_gmem_i8_ loc("<module>"(#loc1))) attributes {cu_attrs = {max_dynamic_shared_size_bytes = #cuda.dev_max_shared_memory_optin, non_portable_cluster_size_allowed = 1 : i32}, cute.kernel, gpu.kernel, nvvm.reqntid = array<i32: 32, 1, 1>} {
      %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc19)
      %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc19)
      %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc19)
      %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc19)
      %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc20)
      %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc20)
      %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc20)
      %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc20)
      %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc21)
      %lay_7 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc21)
      %lay_8 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc21)
      %lay_9 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc21)
      %lay_10 = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc21)
      %lay_11 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc21)
      %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc21)
      %lay_13 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc21)
      %0 = nvvm.read.ptx.sreg.tid.x : i32 loc(#loc22)
      %1 = nvvm.read.ptx.sreg.tid.y : i32 loc(#loc22)
      %2 = nvvm.read.ptx.sreg.tid.z : i32 loc(#loc22)
      %c10_i32 = arith.constant 10 : i32 loc(#loc17)
      %3 = arith.cmpi slt, %0, %c10_i32 : i32 loc(#loc23)
      %c-1_i32 = arith.constant -1 : i32 loc(#loc24)
      %4 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred p;\0A\09\0A            setp.ne.b32 p, $1, 0;\0A\09\0A            vote.sync.ballot.b32 $0, p, $2;\0A\09\0A            }", "=r,r,i" %3, %c-1_i32 : (i1, i32) -> i32 loc(#loc17)
      %5 = arith.cmpi slt, %0, %c10_i32 : i32 loc(#loc23)
      %c-1_i32_14 = arith.constant -1 : i32 loc(#loc25)
      %6 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.any.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %5, %c-1_i32_14 : (i1, i32) -> i1 loc(#loc17)
      %7 = arith.cmpi slt, %0, %c10_i32 : i32 loc(#loc23)
      %c-1_i32_15 = arith.constant -1 : i32 loc(#loc26)
      %8 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.all.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %7, %c-1_i32_15 : (i1, i32) -> i1 loc(#loc17)
      %9 = arith.cmpi slt, %0, %c10_i32 : i32 loc(#loc23)
      %c-1_i32_16 = arith.constant -1 : i32 loc(#loc27)
      %10 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.uni.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %9, %c-1_i32_16 : (i1, i32) -> i1 loc(#loc17)
      %coord = cute.make_coord(%0) : (i32) -> !cute.coord<"?"> loc(#loc28)
      cute.memref.store(%arg0, %coord, %4) : (!memref_gmem_i32_, !cute.coord<"?">, i32) -> () loc(#loc28)
      %11 = arith.extui %6 : i1 to i8 loc(#loc17)
      %coord_17 = cute.make_coord(%0) : (i32) -> !cute.coord<"?"> loc(#loc29)
      cute.memref.store(%arg1, %coord_17, %11) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc29)
      %12 = arith.extui %8 : i1 to i8 loc(#loc17)
      %coord_18 = cute.make_coord(%0) : (i32) -> !cute.coord<"?"> loc(#loc30)
      cute.memref.store(%arg2, %coord_18, %12) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc30)
      %13 = arith.extui %10 : i1 to i8 loc(#loc17)
      %coord_19 = cute.make_coord(%0) : (i32) -> !cute.coord<"?"> loc(#loc31)
      cute.memref.store(%arg3, %coord_19, %13) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc31)
      return loc(#loc17)
    } loc(#loc18)
  } loc(#loc17)
  func.func @cutlass_vote_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_True(%arg0: !memref_gmem_i32_ loc("<module>"(#loc)), %arg1: !memref_gmem_i8_ loc("<module>"(#loc)), %arg2: !memref_gmem_i8_ loc("<module>"(#loc)), %arg3: !memref_gmem_i8_ loc("<module>"(#loc))) -> i32 attributes {llvm.emit_c_interface} {
    %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc19)
    %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc19)
    %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc19)
    %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc19)
    %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc32)
    %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc32)
    %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc32)
    %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc32)
    %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc21)
    %lay_7 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc21)
    %lay_8 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc21)
    %lay_9 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc21)
    %int_tuple = cute.make_int_tuple() : () -> !cute.int_tuple<"32"> loc(#loc33)
    %sz = cute.size(%int_tuple) <{mode = [0]}> : (!cute.int_tuple<"32">) -> !cute.int_tuple<"32"> loc(#loc33)
    %e0 = cute.get_leaves(%sz) : !cute.int_tuple<"32"> loc(#loc33)
    %lay_10 = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc21)
    %lay_11 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc21)
    %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc21)
    %lay_13 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc21)
    %c0_i32 = arith.constant 0 : i32 loc(#loc17)
    %c0_i64 = arith.constant 0 : i64 loc(#loc17)
    %0 = cuda.cast %c0_i64 : i64 -> !cuda.stream loc(#loc18)
    %1 = arith.extsi %c0_i32 : i32 to i64 loc(#loc17)
    %c32_i32 = arith.constant 32 : i32 loc(#loc17)
    %c1_i32 = arith.constant 1 : i32 loc(#loc17)
    %2 = cuda.launch_cfg.create<max_attrs = 3 : i32> (blockDim = (%c32_i32, %c1_i32, %c1_i32), dynamicSmemBytes = %1, gridDim = (%c1_i32, %c1_i32, %c1_i32), stream = %0) : i32, i32, i32, i64, i32, i32, i32, !cuda.stream -> !cuda.launch_cfg<max_attrs = 3> loc(#loc18)
    %c0_i32_14 = arith.constant 0 : i32 loc(#loc17)
    cuda.launch_cfg.programmatic_stream_serialization_allowed[%2] %c0_i32_14 : !cuda.launch_cfg<max_attrs = 3>, i32 loc(#loc18)
    %c0_i32_15 = arith.constant 0 : i32 loc(#loc18)
    cuda.launch_cfg.cooperative[%2] %c0_i32_15 : !cuda.launch_cfg<max_attrs = 3>, i32 loc(#loc18)
    %3 = cuda.launch_ex @kernels::@kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_True_0<%2> (%arg0, %arg1, %arg2, %arg3) {assume_kernel_attr = #cuda.assume_kernel_attr<true>} : !cuda.launch_cfg<max_attrs = 3>, (!memref_gmem_i32_, !memref_gmem_i8_, !memref_gmem_i8_, !memref_gmem_i8_) -> !cuda.result loc(#loc18)
    %4 = cuda.cast %3 : !cuda.result -> i32 loc(#loc18)
    cuda.return_if_error %4 : i32 loc(#loc18)
    %c0_i32_16 = arith.constant 0 : i32 loc(#loc17)
    return %c0_i32_16 : i32 loc(#loc17)
  } loc(#loc17)
} loc(#loc17)
#loc2 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":625:0)
#loc3 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":222:0)
#loc4 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":209:0)
#loc5 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":144:0)
#loc6 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/typing.py":847:0)
#loc7 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":147:0)
#loc8 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":152:0)
#loc9 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":157:0)
#loc10 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":162:0)
#loc11 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":167:0)
#loc12 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":168:0)
#loc13 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":169:0)
#loc14 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":170:0)
#loc15 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/runtime.py":397:0)
#loc16 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":189:0)
#loc19 = loc("fop_args = list(fop.regions[0].blocks[0].arguments)"(#loc2))
#loc20 = loc("return _Tensor("(#loc3))
#loc21 = loc("return f\22tensor<{pretty_str(self.iterator)} o {pretty_str(self.layout)}>\22"(#loc4))
#loc22 = loc("tidx, _, _ = cute.arch.thread_idx()"(#loc5))
#loc23 = loc("res_val = op(lhs_val, rhs_val)"(#loc6))
#loc24 = loc("ptx_vote_ballot_sync(tidx < 10)"(#loc7))
#loc25 = loc("ptx_vote_any_sync(tidx < 10)"(#loc8))
#loc26 = loc("ptx_vote_all_sync(tidx < 10)"(#loc9))
#loc27 = loc("ptx_vote_uni_sync(tidx < 10)"(#loc10))
#loc28 = loc("mBallot[tidx] = vote_ballot"(#loc11))
#loc29 = loc("mAny[tidx] = vote_any"(#loc12))
#loc30 = loc("mAll[tidx] = vote_all"(#loc13))
#loc31 = loc("mUni[tidx] = vote_uni"(#loc14))
#loc32 = loc("return CoreTensor(values[0].value, self._dtype)"(#loc15))
#loc33 = loc("block=[cute.size(WARP_SIZE, mode=[0]), 1, 1],"(#loc16))



!memref_gmem_i32_ = !cute.memref<i32, gmem, "(?):(1)">
!memref_gmem_i8_ = !cute.memref<i8, gmem, "(?):(1)">
#loc = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":174:0)
#loc1 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":137:0)
#loc17 = loc("<module>"(#loc))
#loc18 = loc("<module>"(#loc1))
module attributes {gpu.container_module} {
  gpu.module @kernels {
    cuda.kernel @kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_False_0(%arg0: !memref_gmem_i32_ loc("<module>"(#loc1)), %arg1: !memref_gmem_i8_ loc("<module>"(#loc1)), %arg2: !memref_gmem_i8_ loc("<module>"(#loc1)), %arg3: !memref_gmem_i8_ loc("<module>"(#loc1))) attributes {cu_attrs = {max_dynamic_shared_size_bytes = #cuda.dev_max_shared_memory_optin, non_portable_cluster_size_allowed = 1 : i32}, cute.kernel, gpu.kernel, nvvm.reqntid = array<i32: 32, 1, 1>} {
      %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc19)
      %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc19)
      %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc19)
      %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc19)
      %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc20)
      %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc20)
      %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc20)
      %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc20)
      %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc21)
      %lay_7 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc21)
      %lay_8 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc21)
      %lay_9 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc21)
      %lay_10 = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc21)
      %lay_11 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc21)
      %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc21)
      %lay_13 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc21)
      %0 = nvvm.read.ptx.sreg.tid.x : i32 loc(#loc22)
      %1 = nvvm.read.ptx.sreg.tid.y : i32 loc(#loc22)
      %2 = nvvm.read.ptx.sreg.tid.z : i32 loc(#loc22)
      %c10_i32 = arith.constant 10 : i32 loc(#loc17)
      %3 = arith.cmpi slt, %0, %c10_i32 : i32 loc(#loc23)
      %c-1_i32 = arith.constant -1 : i32 loc(#loc24)
      %4 = nvvm.vote.ballot.sync %c-1_i32, %3 : i32 loc(#loc24)
      %5 = arith.cmpi slt, %0, %c10_i32 : i32 loc(#loc23)
      %c-1_i32_14 = arith.constant -1 : i32 loc(#loc25)
      %6 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.any.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %5, %c-1_i32_14 : (i1, i32) -> i1 loc(#loc25)
      %7 = arith.cmpi slt, %0, %c10_i32 : i32 loc(#loc23)
      %c-1_i32_15 = arith.constant -1 : i32 loc(#loc26)
      %8 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.all.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %7, %c-1_i32_15 : (i1, i32) -> i1 loc(#loc26)
      %9 = arith.cmpi slt, %0, %c10_i32 : i32 loc(#loc23)
      %c-1_i32_16 = arith.constant -1 : i32 loc(#loc27)
      %10 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.uni.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %9, %c-1_i32_16 : (i1, i32) -> i1 loc(#loc27)
      %coord = cute.make_coord(%0) : (i32) -> !cute.coord<"?"> loc(#loc28)
      cute.memref.store(%arg0, %coord, %4) : (!memref_gmem_i32_, !cute.coord<"?">, i32) -> () loc(#loc28)
      %11 = arith.extui %6 : i1 to i8 loc(#loc17)
      %coord_17 = cute.make_coord(%0) : (i32) -> !cute.coord<"?"> loc(#loc29)
      cute.memref.store(%arg1, %coord_17, %11) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc29)
      %12 = arith.extui %8 : i1 to i8 loc(#loc17)
      %coord_18 = cute.make_coord(%0) : (i32) -> !cute.coord<"?"> loc(#loc30)
      cute.memref.store(%arg2, %coord_18, %12) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc30)
      %13 = arith.extui %10 : i1 to i8 loc(#loc17)
      %coord_19 = cute.make_coord(%0) : (i32) -> !cute.coord<"?"> loc(#loc31)
      cute.memref.store(%arg3, %coord_19, %13) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc31)
      return loc(#loc17)
    } loc(#loc18)
  } loc(#loc17)
  func.func @cutlass_vote_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_False(%arg0: !memref_gmem_i32_ loc("<module>"(#loc)), %arg1: !memref_gmem_i8_ loc("<module>"(#loc)), %arg2: !memref_gmem_i8_ loc("<module>"(#loc)), %arg3: !memref_gmem_i8_ loc("<module>"(#loc))) -> i32 attributes {llvm.emit_c_interface} {
    %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc19)
    %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc19)
    %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc19)
    %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc19)
    %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc32)
    %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc32)
    %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc32)
    %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc32)
    %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc21)
    %lay_7 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc21)
    %lay_8 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc21)
    %lay_9 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc21)
    %int_tuple = cute.make_int_tuple() : () -> !cute.int_tuple<"32"> loc(#loc33)
    %sz = cute.size(%int_tuple) <{mode = [0]}> : (!cute.int_tuple<"32">) -> !cute.int_tuple<"32"> loc(#loc33)
    %e0 = cute.get_leaves(%sz) : !cute.int_tuple<"32"> loc(#loc33)
    %lay_10 = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc21)
    %lay_11 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc21)
    %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc21)
    %lay_13 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc21)
    %c0_i32 = arith.constant 0 : i32 loc(#loc17)
    %c0_i64 = arith.constant 0 : i64 loc(#loc17)
    %0 = cuda.cast %c0_i64 : i64 -> !cuda.stream loc(#loc18)
    %1 = arith.extsi %c0_i32 : i32 to i64 loc(#loc17)
    %c32_i32 = arith.constant 32 : i32 loc(#loc17)
    %c1_i32 = arith.constant 1 : i32 loc(#loc17)
    %2 = cuda.launch_cfg.create<max_attrs = 3 : i32> (blockDim = (%c32_i32, %c1_i32, %c1_i32), dynamicSmemBytes = %1, gridDim = (%c1_i32, %c1_i32, %c1_i32), stream = %0) : i32, i32, i32, i64, i32, i32, i32, !cuda.stream -> !cuda.launch_cfg<max_attrs = 3> loc(#loc18)
    %c0_i32_14 = arith.constant 0 : i32 loc(#loc17)
    cuda.launch_cfg.programmatic_stream_serialization_allowed[%2] %c0_i32_14 : !cuda.launch_cfg<max_attrs = 3>, i32 loc(#loc18)
    %c0_i32_15 = arith.constant 0 : i32 loc(#loc18)
    cuda.launch_cfg.cooperative[%2] %c0_i32_15 : !cuda.launch_cfg<max_attrs = 3>, i32 loc(#loc18)
    %3 = cuda.launch_ex @kernels::@kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_False_0<%2> (%arg0, %arg1, %arg2, %arg3) {assume_kernel_attr = #cuda.assume_kernel_attr<true>} : !cuda.launch_cfg<max_attrs = 3>, (!memref_gmem_i32_, !memref_gmem_i8_, !memref_gmem_i8_, !memref_gmem_i8_) -> !cuda.result loc(#loc18)
    %4 = cuda.cast %3 : !cuda.result -> i32 loc(#loc18)
    cuda.return_if_error %4 : i32 loc(#loc18)
    %c0_i32_16 = arith.constant 0 : i32 loc(#loc17)
    return %c0_i32_16 : i32 loc(#loc17)
  } loc(#loc17)
} loc(#loc17)
#loc2 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":625:0)
#loc3 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":222:0)
#loc4 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":209:0)
#loc5 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":144:0)
#loc6 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/typing.py":847:0)
#loc7 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":149:0)
#loc8 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":154:0)
#loc9 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":159:0)
#loc10 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":164:0)
#loc11 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":167:0)
#loc12 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":168:0)
#loc13 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":169:0)
#loc14 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":170:0)
#loc15 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/runtime.py":397:0)
#loc16 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":189:0)
#loc19 = loc("fop_args = list(fop.regions[0].blocks[0].arguments)"(#loc2))
#loc20 = loc("return _Tensor("(#loc3))
#loc21 = loc("return f\22tensor<{pretty_str(self.iterator)} o {pretty_str(self.layout)}>\22"(#loc4))
#loc22 = loc("tidx, _, _ = cute.arch.thread_idx()"(#loc5))
#loc23 = loc("res_val = op(lhs_val, rhs_val)"(#loc6))
#loc24 = loc("else cute.arch.vote_ballot_sync(tidx < 10)"(#loc7))
#loc25 = loc("else cute.arch.vote_any_sync(tidx < 10)"(#loc8))
#loc26 = loc("else cute.arch.vote_all_sync(tidx < 10)"(#loc9))
#loc27 = loc("else cute.arch.vote_uni_sync(tidx < 10)"(#loc10))
#loc28 = loc("mBallot[tidx] = vote_ballot"(#loc11))
#loc29 = loc("mAny[tidx] = vote_any"(#loc12))
#loc30 = loc("mAll[tidx] = vote_all"(#loc13))
#loc31 = loc("mUni[tidx] = vote_uni"(#loc14))
#loc32 = loc("return CoreTensor(values[0].value, self._dtype)"(#loc15))
#loc33 = loc("block=[cute.size(WARP_SIZE, mode=[0]), 1, 1],"(#loc16))

