

!memref_gmem_i32_ = !cute.memref<i32, gmem, "(?):(1)">
!memref_gmem_i8_ = !cute.memref<i8, gmem, "(?):(1)">
#loc = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1158:0)
#loc1 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":181:0)
#loc19 = loc("loc = self.get_location(frame)"(#loc))
#loc20 = loc("vote_kernel("(#loc1))
module attributes {gpu.container_module} {
  gpu.module @kernels {
    cuda.kernel @kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_True_0(%arg0: !memref_gmem_i32_ loc("vote_kernel("(#loc1)), %arg1: !memref_gmem_i8_ loc("vote_kernel("(#loc1)), %arg2: !memref_gmem_i8_ loc("vote_kernel("(#loc1)), %arg3: !memref_gmem_i8_ loc("vote_kernel("(#loc1))) attributes {cu_attrs = {max_dynamic_shared_size_bytes = #cuda.dev_max_shared_memory_optin, non_portable_cluster_size_allowed = 1 : i32}, cute.kernel, gpu.kernel, nvvm.reqntid = array<i32: 32, 1, 1>} {
      %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc21)
      %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc21)
      %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc21)
      %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc21)
      %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc22)
      %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc22)
      %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc22)
      %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc22)
      %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc23)
      %0 = cute.get_shape(%lay) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
      %e0 = cute.get_leaves(%0) : !cute.shape<"(?)"> loc(#loc24)
      %itup = cute.to_int_tuple(%e0) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
      %1 = cute.get_scalars(%itup) : !cute.int_tuple<"?"> loc(#loc24)
      %2 = cute.get_stride(%lay) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
      %e0_7 = cute.get_leaves(%2) : !cute.stride<"(1)"> loc(#loc24)
      %lay_8 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc23)
      %3 = cute.get_shape(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
      %e0_9 = cute.get_leaves(%3) : !cute.shape<"(?)"> loc(#loc24)
      %itup_10 = cute.to_int_tuple(%e0_9) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
      %4 = cute.get_scalars(%itup_10) : !cute.int_tuple<"?"> loc(#loc24)
      %5 = cute.get_stride(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
      %e0_11 = cute.get_leaves(%5) : !cute.stride<"(1)"> loc(#loc24)
      %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc23)
      %6 = cute.get_shape(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
      %e0_13 = cute.get_leaves(%6) : !cute.shape<"(?)"> loc(#loc24)
      %itup_14 = cute.to_int_tuple(%e0_13) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
      %7 = cute.get_scalars(%itup_14) : !cute.int_tuple<"?"> loc(#loc24)
      %8 = cute.get_stride(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
      %e0_15 = cute.get_leaves(%8) : !cute.stride<"(1)"> loc(#loc24)
      %lay_16 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc23)
      %9 = cute.get_shape(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
      %e0_17 = cute.get_leaves(%9) : !cute.shape<"(?)"> loc(#loc24)
      %itup_18 = cute.to_int_tuple(%e0_17) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
      %10 = cute.get_scalars(%itup_18) : !cute.int_tuple<"?"> loc(#loc24)
      %11 = cute.get_stride(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
      %e0_19 = cute.get_leaves(%11) : !cute.stride<"(1)"> loc(#loc24)
      %12 = nvvm.read.ptx.sreg.tid.x : i32 loc(#loc25)
      %13 = nvvm.read.ptx.sreg.tid.y : i32 loc(#loc25)
      %14 = nvvm.read.ptx.sreg.tid.z : i32 loc(#loc25)
      %c10_i32 = arith.constant 10 : i32 loc(#loc26)
      %15 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc27)
      %c-1_i32 = arith.constant -1 : i32 loc(#loc28)
      %16 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred p;\0A\09\0A            setp.ne.b32 p, $1, 0;\0A\09\0A            vote.sync.ballot.b32 $0, p, $2;\0A\09\0A            }", "=r,r,i" %15, %c-1_i32 : (i1, i32) -> i32 loc(#loc26)
      %17 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc27)
      %c-1_i32_20 = arith.constant -1 : i32 loc(#loc29)
      %18 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.any.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %17, %c-1_i32_20 : (i1, i32) -> i1 loc(#loc26)
      %19 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc27)
      %c-1_i32_21 = arith.constant -1 : i32 loc(#loc30)
      %20 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.all.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %19, %c-1_i32_21 : (i1, i32) -> i1 loc(#loc26)
      %21 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc27)
      %c-1_i32_22 = arith.constant -1 : i32 loc(#loc31)
      %22 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.uni.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %21, %c-1_i32_22 : (i1, i32) -> i1 loc(#loc26)
      %coord = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc32)
      cute.memref.store(%arg0, %coord, %16) : (!memref_gmem_i32_, !cute.coord<"?">, i32) -> () loc(#loc32)
      %23 = arith.extui %18 : i1 to i8 loc(#loc26)
      %coord_23 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc33)
      cute.memref.store(%arg1, %coord_23, %23) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc33)
      %24 = arith.extui %20 : i1 to i8 loc(#loc26)
      %coord_24 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc34)
      cute.memref.store(%arg2, %coord_24, %24) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc34)
      %25 = arith.extui %22 : i1 to i8 loc(#loc26)
      %coord_25 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc35)
      cute.memref.store(%arg3, %coord_25, %25) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc35)
      return loc(#loc26)
    } loc(#loc20)
  } loc(#loc19)
  func.func @cutlass_vote_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_True(%arg0: !memref_gmem_i32_ loc("loc = self.get_location(frame)"(#loc)), %arg1: !memref_gmem_i8_ loc("loc = self.get_location(frame)"(#loc)), %arg2: !memref_gmem_i8_ loc("loc = self.get_location(frame)"(#loc)), %arg3: !memref_gmem_i8_ loc("loc = self.get_location(frame)"(#loc))) -> i32 attributes {llvm.emit_c_interface} {
    %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc21)
    %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc21)
    %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc21)
    %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc21)
    %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc36)
    %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc36)
    %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc36)
    %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc36)
    %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc23)
    %0 = cute.get_shape(%lay) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0 = cute.get_leaves(%0) : !cute.shape<"(?)"> loc(#loc24)
    %itup = cute.to_int_tuple(%e0) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %1 = cute.get_scalars(%itup) : !cute.int_tuple<"?"> loc(#loc24)
    %2 = cute.get_stride(%lay) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_7 = cute.get_leaves(%2) : !cute.stride<"(1)"> loc(#loc24)
    %lay_8 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc23)
    %3 = cute.get_shape(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_9 = cute.get_leaves(%3) : !cute.shape<"(?)"> loc(#loc24)
    %itup_10 = cute.to_int_tuple(%e0_9) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %4 = cute.get_scalars(%itup_10) : !cute.int_tuple<"?"> loc(#loc24)
    %5 = cute.get_stride(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_11 = cute.get_leaves(%5) : !cute.stride<"(1)"> loc(#loc24)
    %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc23)
    %6 = cute.get_shape(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_13 = cute.get_leaves(%6) : !cute.shape<"(?)"> loc(#loc24)
    %itup_14 = cute.to_int_tuple(%e0_13) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %7 = cute.get_scalars(%itup_14) : !cute.int_tuple<"?"> loc(#loc24)
    %8 = cute.get_stride(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_15 = cute.get_leaves(%8) : !cute.stride<"(1)"> loc(#loc24)
    %lay_16 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc23)
    %9 = cute.get_shape(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_17 = cute.get_leaves(%9) : !cute.shape<"(?)"> loc(#loc24)
    %itup_18 = cute.to_int_tuple(%e0_17) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %10 = cute.get_scalars(%itup_18) : !cute.int_tuple<"?"> loc(#loc24)
    %11 = cute.get_stride(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_19 = cute.get_leaves(%11) : !cute.stride<"(1)"> loc(#loc24)
    %int_tuple = cute.make_int_tuple() : () -> !cute.int_tuple<"32"> loc(#loc37)
    %sz = cute.size(%int_tuple) <{mode = [0]}> : (!cute.int_tuple<"32">) -> !cute.int_tuple<"32"> loc(#loc37)
    %e0_20 = cute.get_leaves(%sz) : !cute.int_tuple<"32"> loc(#loc37)
    %lay_21 = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc23)
    %12 = cute.get_shape(%lay_21) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_22 = cute.get_leaves(%12) : !cute.shape<"(?)"> loc(#loc24)
    %itup_23 = cute.to_int_tuple(%e0_22) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %13 = cute.get_scalars(%itup_23) : !cute.int_tuple<"?"> loc(#loc24)
    %14 = cute.get_stride(%lay_21) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_24 = cute.get_leaves(%14) : !cute.stride<"(1)"> loc(#loc24)
    %lay_25 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc23)
    %15 = cute.get_shape(%lay_25) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_26 = cute.get_leaves(%15) : !cute.shape<"(?)"> loc(#loc24)
    %itup_27 = cute.to_int_tuple(%e0_26) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %16 = cute.get_scalars(%itup_27) : !cute.int_tuple<"?"> loc(#loc24)
    %17 = cute.get_stride(%lay_25) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_28 = cute.get_leaves(%17) : !cute.stride<"(1)"> loc(#loc24)
    %lay_29 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc23)
    %18 = cute.get_shape(%lay_29) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_30 = cute.get_leaves(%18) : !cute.shape<"(?)"> loc(#loc24)
    %itup_31 = cute.to_int_tuple(%e0_30) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %19 = cute.get_scalars(%itup_31) : !cute.int_tuple<"?"> loc(#loc24)
    %20 = cute.get_stride(%lay_29) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_32 = cute.get_leaves(%20) : !cute.stride<"(1)"> loc(#loc24)
    %lay_33 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc23)
    %21 = cute.get_shape(%lay_33) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_34 = cute.get_leaves(%21) : !cute.shape<"(?)"> loc(#loc24)
    %itup_35 = cute.to_int_tuple(%e0_34) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %22 = cute.get_scalars(%itup_35) : !cute.int_tuple<"?"> loc(#loc24)
    %23 = cute.get_stride(%lay_33) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_36 = cute.get_leaves(%23) : !cute.stride<"(1)"> loc(#loc24)
    %c0_i32 = arith.constant 0 : i32 loc(#loc26)
    %c0_i64 = arith.constant 0 : i64 loc(#loc26)
    %24 = cuda.cast %c0_i64 : i64 -> !cuda.stream loc(#loc20)
    %25 = arith.extsi %c0_i32 : i32 to i64 loc(#loc26)
    %c32_i32 = arith.constant 32 : i32 loc(#loc26)
    %c1_i32 = arith.constant 1 : i32 loc(#loc26)
    %26 = cuda.launch_cfg.create<max_attrs = 2 : i32> (blockDim = (%c32_i32, %c1_i32, %c1_i32), dynamicSmemBytes = %25, gridDim = (%c1_i32, %c1_i32, %c1_i32), stream = %24) : i32, i32, i32, i64, i32, i32, i32, !cuda.stream -> !cuda.launch_cfg<max_attrs = 2> loc(#loc20)
    %27 = cuda.launch_ex @kernels::@kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_True_0<%26> (%arg0, %arg1, %arg2, %arg3) : !cuda.launch_cfg<max_attrs = 2>, (!memref_gmem_i32_, !memref_gmem_i8_, !memref_gmem_i8_, !memref_gmem_i8_) -> !cuda.result loc(#loc20)
    %28 = cuda.cast %27 : !cuda.result -> i32 loc(#loc20)
    cuda.return_if_error %28 : i32 loc(#loc20)
    %c0_i32_37 = arith.constant 0 : i32 loc(#loc26)
    return %c0_i32_37 : i32 loc(#loc19)
  } loc(#loc19)
} loc(#loc19)
#loc2 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":658:0)
#loc3 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":171:0)
#loc4 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":158:0)
#loc5 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":802:0)
#loc6 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":144:0)
#loc7 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1347:0)
#loc8 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/typing.py":846:0)
#loc9 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":147:0)
#loc10 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":152:0)
#loc11 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":157:0)
#loc12 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":162:0)
#loc13 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":167:0)
#loc14 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":168:0)
#loc15 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":169:0)
#loc16 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":170:0)
#loc17 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/runtime.py":388:0)
#loc18 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":189:0)
#loc21 = loc("fop_args = list(fop.regions[0].blocks[0].arguments)"(#loc2))
#loc22 = loc("return _Tensor("(#loc3))
#loc23 = loc("return f\22tensor<{pretty_str(self.iterator)} o {pretty_str(self.layout)}>\22"(#loc4))
#loc24 = loc("return f\22{pretty_str(self.shape)}:{pretty_str(self.stride)}\22"(#loc5))
#loc25 = loc("tidx, _, _ = cute.arch.thread_idx()"(#loc6))
#loc26 = loc("with ir.Context(), self.get_location(frame):"(#loc7))
#loc27 = loc("res_val = op(lhs_val, rhs_val)"(#loc8))
#loc28 = loc("ptx_vote_ballot_sync(tidx < 10)"(#loc9))
#loc29 = loc("ptx_vote_any_sync(tidx < 10)"(#loc10))
#loc30 = loc("ptx_vote_all_sync(tidx < 10)"(#loc11))
#loc31 = loc("ptx_vote_uni_sync(tidx < 10)"(#loc12))
#loc32 = loc("mBallot[tidx] = vote_ballot"(#loc13))
#loc33 = loc("mAny[tidx] = vote_any"(#loc14))
#loc34 = loc("mAll[tidx] = vote_all"(#loc15))
#loc35 = loc("mUni[tidx] = vote_uni"(#loc16))
#loc36 = loc("return CoreTensor(values[0].value, self._dtype)"(#loc17))
#loc37 = loc("block=[cute.size(WARP_SIZE, mode=[0]), 1, 1],"(#loc18))



!memref_gmem_i32_ = !cute.memref<i32, gmem, "(?):(1)">
!memref_gmem_i8_ = !cute.memref<i8, gmem, "(?):(1)">
#loc = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1158:0)
#loc1 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":181:0)
#loc19 = loc("loc = self.get_location(frame)"(#loc))
#loc20 = loc("vote_kernel("(#loc1))
module attributes {gpu.container_module} {
  gpu.module @kernels {
    cuda.kernel @kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_False_0(%arg0: !memref_gmem_i32_ loc("vote_kernel("(#loc1)), %arg1: !memref_gmem_i8_ loc("vote_kernel("(#loc1)), %arg2: !memref_gmem_i8_ loc("vote_kernel("(#loc1)), %arg3: !memref_gmem_i8_ loc("vote_kernel("(#loc1))) attributes {cu_attrs = {max_dynamic_shared_size_bytes = #cuda.dev_max_shared_memory_optin, non_portable_cluster_size_allowed = 1 : i32}, cute.kernel, gpu.kernel, nvvm.reqntid = array<i32: 32, 1, 1>} {
      %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc21)
      %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc21)
      %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc21)
      %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc21)
      %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc22)
      %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc22)
      %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc22)
      %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc22)
      %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc23)
      %0 = cute.get_shape(%lay) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
      %e0 = cute.get_leaves(%0) : !cute.shape<"(?)"> loc(#loc24)
      %itup = cute.to_int_tuple(%e0) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
      %1 = cute.get_scalars(%itup) : !cute.int_tuple<"?"> loc(#loc24)
      %2 = cute.get_stride(%lay) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
      %e0_7 = cute.get_leaves(%2) : !cute.stride<"(1)"> loc(#loc24)
      %lay_8 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc23)
      %3 = cute.get_shape(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
      %e0_9 = cute.get_leaves(%3) : !cute.shape<"(?)"> loc(#loc24)
      %itup_10 = cute.to_int_tuple(%e0_9) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
      %4 = cute.get_scalars(%itup_10) : !cute.int_tuple<"?"> loc(#loc24)
      %5 = cute.get_stride(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
      %e0_11 = cute.get_leaves(%5) : !cute.stride<"(1)"> loc(#loc24)
      %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc23)
      %6 = cute.get_shape(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
      %e0_13 = cute.get_leaves(%6) : !cute.shape<"(?)"> loc(#loc24)
      %itup_14 = cute.to_int_tuple(%e0_13) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
      %7 = cute.get_scalars(%itup_14) : !cute.int_tuple<"?"> loc(#loc24)
      %8 = cute.get_stride(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
      %e0_15 = cute.get_leaves(%8) : !cute.stride<"(1)"> loc(#loc24)
      %lay_16 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc23)
      %9 = cute.get_shape(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
      %e0_17 = cute.get_leaves(%9) : !cute.shape<"(?)"> loc(#loc24)
      %itup_18 = cute.to_int_tuple(%e0_17) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
      %10 = cute.get_scalars(%itup_18) : !cute.int_tuple<"?"> loc(#loc24)
      %11 = cute.get_stride(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
      %e0_19 = cute.get_leaves(%11) : !cute.stride<"(1)"> loc(#loc24)
      %12 = nvvm.read.ptx.sreg.tid.x : i32 loc(#loc25)
      %13 = nvvm.read.ptx.sreg.tid.y : i32 loc(#loc25)
      %14 = nvvm.read.ptx.sreg.tid.z : i32 loc(#loc25)
      %c10_i32 = arith.constant 10 : i32 loc(#loc26)
      %15 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc27)
      %c-1_i32 = arith.constant -1 : i32 loc(#loc28)
      %16 = nvvm.vote.ballot.sync %c-1_i32, %15 : i32 loc(#loc28)
      %17 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc27)
      %c-1_i32_20 = arith.constant -1 : i32 loc(#loc29)
      %18 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.any.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %17, %c-1_i32_20 : (i1, i32) -> i1 loc(#loc29)
      %19 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc27)
      %c-1_i32_21 = arith.constant -1 : i32 loc(#loc30)
      %20 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.all.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %19, %c-1_i32_21 : (i1, i32) -> i1 loc(#loc30)
      %21 = arith.cmpi slt, %12, %c10_i32 : i32 loc(#loc27)
      %c-1_i32_22 = arith.constant -1 : i32 loc(#loc31)
      %22 = llvm.inline_asm has_side_effects asm_dialect = att "{\0A\09\0A            .reg .pred ps;\0A\09\0A            .reg .pred pd;\0A\09\0A            setp.ne.b32 ps, $1, 0;\0A\09\0A            vote.sync.uni.pred pd, ps, $2;\0A\09\0A            selp.b32 $0, 1, 0, pd;\0A\09\0A            }", "=r,r,i" %21, %c-1_i32_22 : (i1, i32) -> i1 loc(#loc31)
      %coord = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc32)
      cute.memref.store(%arg0, %coord, %16) : (!memref_gmem_i32_, !cute.coord<"?">, i32) -> () loc(#loc32)
      %23 = arith.extui %18 : i1 to i8 loc(#loc26)
      %coord_23 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc33)
      cute.memref.store(%arg1, %coord_23, %23) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc33)
      %24 = arith.extui %20 : i1 to i8 loc(#loc26)
      %coord_24 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc34)
      cute.memref.store(%arg2, %coord_24, %24) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc34)
      %25 = arith.extui %22 : i1 to i8 loc(#loc26)
      %coord_25 = cute.make_coord(%12) : (i32) -> !cute.coord<"?"> loc(#loc35)
      cute.memref.store(%arg3, %coord_25, %25) : (!memref_gmem_i8_, !cute.coord<"?">, i8) -> () loc(#loc35)
      return loc(#loc26)
    } loc(#loc20)
  } loc(#loc19)
  func.func @cutlass_vote_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_Tensorgmemo1_False(%arg0: !memref_gmem_i32_ loc("loc = self.get_location(frame)"(#loc)), %arg1: !memref_gmem_i8_ loc("loc = self.get_location(frame)"(#loc)), %arg2: !memref_gmem_i8_ loc("loc = self.get_location(frame)"(#loc)), %arg3: !memref_gmem_i8_ loc("loc = self.get_location(frame)"(#loc))) -> i32 attributes {llvm.emit_c_interface} {
    %iter = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc21)
    %iter_0 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc21)
    %iter_1 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc21)
    %iter_2 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc21)
    %iter_3 = cute.get_iter(%arg0) : !memref_gmem_i32_ loc(#loc36)
    %iter_4 = cute.get_iter(%arg1) : !memref_gmem_i8_ loc(#loc36)
    %iter_5 = cute.get_iter(%arg2) : !memref_gmem_i8_ loc(#loc36)
    %iter_6 = cute.get_iter(%arg3) : !memref_gmem_i8_ loc(#loc36)
    %lay = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc23)
    %0 = cute.get_shape(%lay) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0 = cute.get_leaves(%0) : !cute.shape<"(?)"> loc(#loc24)
    %itup = cute.to_int_tuple(%e0) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %1 = cute.get_scalars(%itup) : !cute.int_tuple<"?"> loc(#loc24)
    %2 = cute.get_stride(%lay) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_7 = cute.get_leaves(%2) : !cute.stride<"(1)"> loc(#loc24)
    %lay_8 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc23)
    %3 = cute.get_shape(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_9 = cute.get_leaves(%3) : !cute.shape<"(?)"> loc(#loc24)
    %itup_10 = cute.to_int_tuple(%e0_9) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %4 = cute.get_scalars(%itup_10) : !cute.int_tuple<"?"> loc(#loc24)
    %5 = cute.get_stride(%lay_8) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_11 = cute.get_leaves(%5) : !cute.stride<"(1)"> loc(#loc24)
    %lay_12 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc23)
    %6 = cute.get_shape(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_13 = cute.get_leaves(%6) : !cute.shape<"(?)"> loc(#loc24)
    %itup_14 = cute.to_int_tuple(%e0_13) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %7 = cute.get_scalars(%itup_14) : !cute.int_tuple<"?"> loc(#loc24)
    %8 = cute.get_stride(%lay_12) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_15 = cute.get_leaves(%8) : !cute.stride<"(1)"> loc(#loc24)
    %lay_16 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc23)
    %9 = cute.get_shape(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_17 = cute.get_leaves(%9) : !cute.shape<"(?)"> loc(#loc24)
    %itup_18 = cute.to_int_tuple(%e0_17) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %10 = cute.get_scalars(%itup_18) : !cute.int_tuple<"?"> loc(#loc24)
    %11 = cute.get_stride(%lay_16) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_19 = cute.get_leaves(%11) : !cute.stride<"(1)"> loc(#loc24)
    %int_tuple = cute.make_int_tuple() : () -> !cute.int_tuple<"32"> loc(#loc37)
    %sz = cute.size(%int_tuple) <{mode = [0]}> : (!cute.int_tuple<"32">) -> !cute.int_tuple<"32"> loc(#loc37)
    %e0_20 = cute.get_leaves(%sz) : !cute.int_tuple<"32"> loc(#loc37)
    %lay_21 = cute.get_layout(%arg0) : !memref_gmem_i32_ loc(#loc23)
    %12 = cute.get_shape(%lay_21) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_22 = cute.get_leaves(%12) : !cute.shape<"(?)"> loc(#loc24)
    %itup_23 = cute.to_int_tuple(%e0_22) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %13 = cute.get_scalars(%itup_23) : !cute.int_tuple<"?"> loc(#loc24)
    %14 = cute.get_stride(%lay_21) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_24 = cute.get_leaves(%14) : !cute.stride<"(1)"> loc(#loc24)
    %lay_25 = cute.get_layout(%arg1) : !memref_gmem_i8_ loc(#loc23)
    %15 = cute.get_shape(%lay_25) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_26 = cute.get_leaves(%15) : !cute.shape<"(?)"> loc(#loc24)
    %itup_27 = cute.to_int_tuple(%e0_26) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %16 = cute.get_scalars(%itup_27) : !cute.int_tuple<"?"> loc(#loc24)
    %17 = cute.get_stride(%lay_25) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_28 = cute.get_leaves(%17) : !cute.stride<"(1)"> loc(#loc24)
    %lay_29 = cute.get_layout(%arg2) : !memref_gmem_i8_ loc(#loc23)
    %18 = cute.get_shape(%lay_29) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_30 = cute.get_leaves(%18) : !cute.shape<"(?)"> loc(#loc24)
    %itup_31 = cute.to_int_tuple(%e0_30) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %19 = cute.get_scalars(%itup_31) : !cute.int_tuple<"?"> loc(#loc24)
    %20 = cute.get_stride(%lay_29) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_32 = cute.get_leaves(%20) : !cute.stride<"(1)"> loc(#loc24)
    %lay_33 = cute.get_layout(%arg3) : !memref_gmem_i8_ loc(#loc23)
    %21 = cute.get_shape(%lay_33) : (!cute.layout<"(?):(1)">) -> !cute.shape<"(?)"> loc(#loc24)
    %e0_34 = cute.get_leaves(%21) : !cute.shape<"(?)"> loc(#loc24)
    %itup_35 = cute.to_int_tuple(%e0_34) : !cute.shape<"?"> to !cute.int_tuple<"?"> loc(#loc24)
    %22 = cute.get_scalars(%itup_35) : !cute.int_tuple<"?"> loc(#loc24)
    %23 = cute.get_stride(%lay_33) : (!cute.layout<"(?):(1)">) -> !cute.stride<"(1)"> loc(#loc24)
    %e0_36 = cute.get_leaves(%23) : !cute.stride<"(1)"> loc(#loc24)
    %c0_i32 = arith.constant 0 : i32 loc(#loc26)
    %c0_i64 = arith.constant 0 : i64 loc(#loc26)
    %24 = cuda.cast %c0_i64 : i64 -> !cuda.stream loc(#loc20)
    %25 = arith.extsi %c0_i32 : i32 to i64 loc(#loc26)
    %c32_i32 = arith.constant 32 : i32 loc(#loc26)
    %c1_i32 = arith.constant 1 : i32 loc(#loc26)
    %26 = cuda.launch_cfg.create<max_attrs = 2 : i32> (blockDim = (%c32_i32, %c1_i32, %c1_i32), dynamicSmemBytes = %25, gridDim = (%c1_i32, %c1_i32, %c1_i32), stream = %24) : i32, i32, i32, i64, i32, i32, i32, !cuda.stream -> !cuda.launch_cfg<max_attrs = 2> loc(#loc20)
    %27 = cuda.launch_ex @kernels::@kernel_cutlass_vote_kernel_tensorptri32gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_tensorptri8gmemo1_False_0<%26> (%arg0, %arg1, %arg2, %arg3) : !cuda.launch_cfg<max_attrs = 2>, (!memref_gmem_i32_, !memref_gmem_i8_, !memref_gmem_i8_, !memref_gmem_i8_) -> !cuda.result loc(#loc20)
    %28 = cuda.cast %27 : !cuda.result -> i32 loc(#loc20)
    cuda.return_if_error %28 : i32 loc(#loc20)
    %c0_i32_37 = arith.constant 0 : i32 loc(#loc26)
    return %c0_i32_37 : i32 loc(#loc19)
  } loc(#loc19)
} loc(#loc19)
#loc2 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":658:0)
#loc3 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":171:0)
#loc4 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":158:0)
#loc5 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":802:0)
#loc6 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":144:0)
#loc7 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1347:0)
#loc8 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/typing.py":846:0)
#loc9 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":149:0)
#loc10 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":154:0)
#loc11 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":159:0)
#loc12 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":164:0)
#loc13 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":167:0)
#loc14 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":168:0)
#loc15 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":169:0)
#loc16 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":170:0)
#loc17 = loc("/usr/local/lib/python3.10/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/runtime.py":388:0)
#loc18 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/inline_ptx.py":189:0)
#loc21 = loc("fop_args = list(fop.regions[0].blocks[0].arguments)"(#loc2))
#loc22 = loc("return _Tensor("(#loc3))
#loc23 = loc("return f\22tensor<{pretty_str(self.iterator)} o {pretty_str(self.layout)}>\22"(#loc4))
#loc24 = loc("return f\22{pretty_str(self.shape)}:{pretty_str(self.stride)}\22"(#loc5))
#loc25 = loc("tidx, _, _ = cute.arch.thread_idx()"(#loc6))
#loc26 = loc("with ir.Context(), self.get_location(frame):"(#loc7))
#loc27 = loc("res_val = op(lhs_val, rhs_val)"(#loc8))
#loc28 = loc("else cute.arch.vote_ballot_sync(tidx < 10)"(#loc9))
#loc29 = loc("else cute.arch.vote_any_sync(tidx < 10)"(#loc10))
#loc30 = loc("else cute.arch.vote_all_sync(tidx < 10)"(#loc11))
#loc31 = loc("else cute.arch.vote_uni_sync(tidx < 10)"(#loc12))
#loc32 = loc("mBallot[tidx] = vote_ballot"(#loc13))
#loc33 = loc("mAny[tidx] = vote_any"(#loc14))
#loc34 = loc("mAll[tidx] = vote_all"(#loc15))
#loc35 = loc("mUni[tidx] = vote_uni"(#loc16))
#loc36 = loc("return CoreTensor(values[0].value, self._dtype)"(#loc17))
#loc37 = loc("block=[cute.size(WARP_SIZE, mode=[0]), 1, 1],"(#loc18))

