name: install-intel-graphics
description: Download and unpack Intel graphics drivers
inputs:
  GPU:
    description: "Install for PVC or BMG gpu"
    type: string
  IGC:
    description: "Use ROLLING or STAGING release"
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Intel graphics drivers
      if: inputs.IGC == 'ROLLING'
      shell: bash
      run: |
        shopt -s expand_aliases
        which sudo || alias sudo=""
        if [[ "${{ inputs.GPU }}" == "BMG" ]] || [[ "${{ inputs.GPU }}" == "PVC" ]]; then
          #purge existing intel graphics packages
          sudo apt-get purge -y 'libigc*' 'intel-igc*' 'libigdgmm*' 'libigdfcl*' \
          'libze-intel-gpu*' 'libze1' 'libze-dev' 'intel-opencl-icd' \
          'intel-metrics-discovery' 'intel-gsc' 'intel-ocloc' || true        
          sudo rm -f /etc/apt/sources.list.d/kobuk-team-ubuntu-intel-graphics-*

          sudo add-apt-repository ppa:kobuk-team/intel-graphics
          sudo apt update
          sudo apt-get install -y libze-intel-gpu1 libze-dev intel-metrics-discovery \
            intel-opencl-icd ocl-icd-opencl-dev clinfo intel-gsc intel-ocloc g++
          dpkg -l | grep libhwloc15 > /dev/null || sudo apt install -y libhwloc15
        else
          exit 1
        fi
    - name: Install Intel graphics drivers
      if: inputs.IGC == 'STAGING'
      shell: bash
      run: |
        shopt -s expand_aliases
        which sudo || alias sudo=""
        if [[ "${{ inputs.GPU }}" == "BMG" ]] || [[ "${{ inputs.GPU }}" == "PVC" ]]; then
          #purge existing intel graphics packages
          sudo apt-get purge -y 'libigc*' 'intel-igc*' 'libigdgmm*' 'libigdfcl*' \
          'libze-intel-gpu*' 'libze1' 'libze-dev' 'intel-opencl-icd' \
          'intel-metrics-discovery' 'intel-gsc' 'intel-ocloc' || true        
          sudo rm -f /etc/apt/sources.list.d/kobuk-team-ubuntu-intel-graphics-*

          sudo add-apt-repository ppa:kobuk-team/intel-graphics-staging
          sudo apt update
          sudo apt-get install -y libze-intel-gpu1 libze-dev intel-metrics-discovery \
            intel-opencl-icd ocl-icd-opencl-dev clinfo intel-gsc intel-ocloc g++
          dpkg -l | grep libhwloc15 > /dev/null || sudo apt install -y libhwloc15
        else
          exit 1
        fi
