

!memref_gmem_f32_ = !cute.memref<f32, gmem, "(8,4):(4,1)">
!memref_gmem_f32_1 = !cute.memref<f32, gmem, "(8,2):(2,1)">
!memref_gmem_f32_2 = !cute.memref<f32, gmem, "(16,2):(2,1)">
!memref_smem_f32_ = !cute.memref<f32, smem, align<32>, "(16,2):(1,16)">
!memref_smem_f32_1 = !cute.memref<f32, smem, align<128>, "(8,4):(1,8)">
!memref_smem_f32_2 = !cute.memref<f32, smem, align<128>, "(8,2):(1,8)">
#loc3 = loc(unknown)
module attributes {gpu.container_module} {
  gpu.module @kernels {
    func.func public @kernel_cutlass_kernel_05_tensorptrf32gmemo8441_10_tensorptrf32gmemo8221_20_tensorptrf32gmemo16221_0(%arg0: !memref_gmem_f32_ loc(unknown), %arg1: !memref_gmem_f32_1 loc(unknown), %arg2: !memref_gmem_f32_2 loc(unknown)) attributes {cute.kernel, gpu.kernel, nvvm.reqntid = array<i32: 1, 1, 1>} {
      %iter = cute.get_iter(%arg0) : !memref_gmem_f32_ loc(#loc52)
      %iter_0 = cute.get_iter(%arg1) : !memref_gmem_f32_1 loc(#loc52)
      %iter_1 = cute.get_iter(%arg2) : !memref_gmem_f32_2 loc(#loc52)
      %iter_2 = cute.get_iter(%arg0) : !memref_gmem_f32_ loc(#loc53)
      %iter_3 = cute.get_iter(%arg1) : !memref_gmem_f32_1 loc(#loc53)
      %iter_4 = cute.get_iter(%arg2) : !memref_gmem_f32_2 loc(#loc53)
      %lay = cute.get_layout(%arg0) : !memref_gmem_f32_ loc(#loc54)
      %0 = cute.get_shape(%lay) : (!cute.layout<"(8,4):(4,1)">) -> !cute.shape<"(8,4)"> loc(#loc55)
      %e0, %e1 = cute.get_leaves(%0) : !cute.shape<"(8,4)"> loc(#loc55)
      %1 = cute.get_stride(%lay) : (!cute.layout<"(8,4):(4,1)">) -> !cute.stride<"(4,1)"> loc(#loc56)
      %e0_5, %e1_6 = cute.get_leaves(%1) : !cute.stride<"(4,1)"> loc(#loc56)
      %lay_7 = cute.get_layout(%arg1) : !memref_gmem_f32_1 loc(#loc54)
      %2 = cute.get_shape(%lay_7) : (!cute.layout<"(8,2):(2,1)">) -> !cute.shape<"(8,2)"> loc(#loc55)
      %e0_8, %e1_9 = cute.get_leaves(%2) : !cute.shape<"(8,2)"> loc(#loc55)
      %3 = cute.get_stride(%lay_7) : (!cute.layout<"(8,2):(2,1)">) -> !cute.stride<"(2,1)"> loc(#loc56)
      %e0_10, %e1_11 = cute.get_leaves(%3) : !cute.stride<"(2,1)"> loc(#loc56)
      %lay_12 = cute.get_layout(%arg2) : !memref_gmem_f32_2 loc(#loc54)
      %4 = cute.get_shape(%lay_12) : (!cute.layout<"(16,2):(2,1)">) -> !cute.shape<"(16,2)"> loc(#loc55)
      %e0_13, %e1_14 = cute.get_leaves(%4) : !cute.shape<"(16,2)"> loc(#loc55)
      %5 = cute.get_stride(%lay_12) : (!cute.layout<"(16,2):(2,1)">) -> !cute.stride<"(2,1)"> loc(#loc56)
      %e0_15, %e1_16 = cute.get_leaves(%5) : !cute.stride<"(2,1)"> loc(#loc56)
      %smem_ptr = cute_nvgpu.arch.get_dyn_smem() : !cute.ptr<i8, smem, align<1024>> loc(#loc57)
      %int_tuple = cute.make_int_tuple() : () -> !cute.int_tuple<"32"> loc(#loc58)
      %tile = cute.make_tile() : () -> !cute.tile<"8:1"> loc(#loc58)
      %shp = cute.ceil_div(%int_tuple, %tile) : !cute.int_tuple<"32">, !cute.tile<"8:1"> loc(#loc58)
      %e0_17 = cute.get_leaves(%shp) : !cute.int_tuple<"4"> loc(#loc58)
      %int_tuple_18 = cute.make_int_tuple() : () -> !cute.int_tuple<"4"> loc(#loc59)
      %ptr = cute.add_offset(%smem_ptr, %int_tuple_18) : (!cute.ptr<i8, smem, align<1024>>, !cute.int_tuple<"4">) -> !cute.ptr<i8, smem, align<4>> loc(#loc59)
      %smem_size = cute_nvgpu.arch.get_dyn_smem_size() : i32 loc(#loc60)
      %c4_i32 = arith.constant 4 : i32 loc(#loc3)
      %6 = arith.cmpi sge, %smem_size, %c4_i32 : i32 loc(#loc61)
      cf.assert %6, "Allocation failed: shared memory allocation exceeds available memory set in kernel launch. Allocated bytes: 4 bytes. Please reduce the allocation or set a larger smem size in kernel launch." loc(#loc60)
      %iter_19 = cute.recast_iter(%smem_ptr) : !cute.ptr<i8, smem, align<1024>> to !cute.ptr<i32, smem, align<1024>> loc(#loc60)
      %7 = cute.ptrtoint(%ptr) : !cute.ptr<i8, smem, align<4>> to i32 loc(#loc62)
      %c128_i32 = arith.constant 128 : i32 loc(#loc3)
      %8 = arith.addi %7, %c128_i32 : i32 loc(#loc63)
      %c1_i32 = arith.constant 1 : i32 loc(#loc3)
      %9 = arith.subi %8, %c1_i32 : i32 loc(#loc63)
      %c-128_i32 = arith.constant -128 : i32 loc(#loc3)
      %10 = arith.andi %9, %c-128_i32 : i32 loc(#loc63)
      %11 = arith.extsi %10 : i32 to i64 loc(#loc3)
      %iv = cute.assume(%11) : (i64) -> !cute.i64<divby 128> loc(#loc62)
      %12 = cute.inttoptr(%iv) : !cute.i64<divby 128> to !cute.ptr<i8, smem, align<128>> loc(#loc62)
      %int_tuple_20 = cute.make_int_tuple() : () -> !cute.int_tuple<"512"> loc(#loc59)
      %ptr_21 = cute.add_offset(%12, %int_tuple_20) : (!cute.ptr<i8, smem, align<128>>, !cute.int_tuple<"512">) -> !cute.ptr<i8, smem, align<128>> loc(#loc59)
      %smem_size_22 = cute_nvgpu.arch.get_dyn_smem_size() : i32 loc(#loc64)
      %c640_i32 = arith.constant 640 : i32 loc(#loc3)
      %13 = arith.cmpi sge, %smem_size_22, %c640_i32 : i32 loc(#loc61)
      cf.assert %13, "Allocation failed: shared memory allocation exceeds available memory set in kernel launch. Allocated bytes: 640 bytes. Please reduce the allocation or set a larger smem size in kernel launch." loc(#loc64)
      %int_tuple_23 = cute.make_int_tuple() : () -> !cute.int_tuple<"0"> loc(#loc65)
      %ptr_24 = cute.add_offset(%12, %int_tuple_23) : (!cute.ptr<i8, smem, align<128>>, !cute.int_tuple<"0">) -> !cute.ptr<i8, smem, align<128>> loc(#loc65)
      %int_tuple_25 = cute.make_int_tuple() : () -> !cute.int_tuple<"128"> loc(#loc66)
      %ptr_26 = cute.add_offset(%12, %int_tuple_25) : (!cute.ptr<i8, smem, align<128>>, !cute.int_tuple<"128">) -> !cute.ptr<i8, smem, align<128>> loc(#loc66)
      %iter_27 = cute.recast_iter(%ptr_26) : !cute.ptr<i8, smem, align<128>> to !cute.ptr<i64, smem, align<128>> loc(#loc67)
      %int_tuple_28 = cute.make_int_tuple() : () -> !cute.int_tuple<"136"> loc(#loc68)
      %ptr_29 = cute.add_offset(%12, %int_tuple_28) : (!cute.ptr<i8, smem, align<128>>, !cute.int_tuple<"136">) -> !cute.ptr<i8, smem, align<8>> loc(#loc68)
      %int_tuple_30 = cute.make_int_tuple() : () -> !cute.int_tuple<"0"> loc(#loc66)
      %ptr_31 = cute.add_offset(%ptr_29, %int_tuple_30) : (!cute.ptr<i8, smem, align<8>>, !cute.int_tuple<"0">) -> !cute.ptr<i8, smem, align<8>> loc(#loc66)
      %iter_32 = cute.recast_iter(%ptr_31) : !cute.ptr<i8, smem, align<8>> to !cute.ptr<f32, smem, align<8>> loc(#loc67)
      %int_tuple_33 = cute.make_int_tuple() : () -> !cute.int_tuple<"4"> loc(#loc66)
      %ptr_34 = cute.add_offset(%ptr_29, %int_tuple_33) : (!cute.ptr<i8, smem, align<8>>, !cute.int_tuple<"4">) -> !cute.ptr<i8, smem, align<4>> loc(#loc66)
      %iter_35 = cute.recast_iter(%ptr_34) : !cute.ptr<i8, smem, align<4>> to !cute.ptr<f32, smem> loc(#loc67)
      %int_tuple_36 = cute.make_int_tuple() : () -> !cute.int_tuple<"256"> loc(#loc65)
      %ptr_37 = cute.add_offset(%12, %int_tuple_36) : (!cute.ptr<i8, smem, align<128>>, !cute.int_tuple<"256">) -> !cute.ptr<i8, smem, align<128>> loc(#loc65)
      %int_tuple_38 = cute.make_int_tuple() : () -> !cute.int_tuple<"384"> loc(#loc66)
      %ptr_39 = cute.add_offset(%12, %int_tuple_38) : (!cute.ptr<i8, smem, align<128>>, !cute.int_tuple<"384">) -> !cute.ptr<i8, smem, align<128>> loc(#loc66)
      %iter_40 = cute.recast_iter(%ptr_39) : !cute.ptr<i8, smem, align<128>> to !cute.ptr<i32, smem, align<128>> loc(#loc67)
      %int_tuple_41 = cute.make_int_tuple() : () -> !cute.int_tuple<"400"> loc(#loc68)
      %ptr_42 = cute.add_offset(%12, %int_tuple_41) : (!cute.ptr<i8, smem, align<128>>, !cute.int_tuple<"400">) -> !cute.ptr<i8, smem, align<16>> loc(#loc68)
      %int_tuple_43 = cute.make_int_tuple() : () -> !cute.int_tuple<"0"> loc(#loc66)
      %ptr_44 = cute.add_offset(%ptr_42, %int_tuple_43) : (!cute.ptr<i8, smem, align<16>>, !cute.int_tuple<"0">) -> !cute.ptr<i8, smem, align<16>> loc(#loc66)
      %iter_45 = cute.recast_iter(%ptr_44) : !cute.ptr<i8, smem, align<16>> to !cute.ptr<f32, smem, align<16>> loc(#loc67)
      %int_tuple_46 = cute.make_int_tuple() : () -> !cute.int_tuple<"4"> loc(#loc66)
      %ptr_47 = cute.add_offset(%ptr_42, %int_tuple_46) : (!cute.ptr<i8, smem, align<16>>, !cute.int_tuple<"4">) -> !cute.ptr<i8, smem, align<4>> loc(#loc66)
      %iter_48 = cute.recast_iter(%ptr_47) : !cute.ptr<i8, smem, align<4>> to !cute.ptr<f32, smem> loc(#loc67)
      %int_tuple_49 = cute.make_int_tuple() : () -> !cute.int_tuple<"64"> loc(#loc59)
      %ptr_50 = cute.add_offset(%ptr_21, %int_tuple_49) : (!cute.ptr<i8, smem, align<128>>, !cute.int_tuple<"64">) -> !cute.ptr<i8, smem, align<64>> loc(#loc59)
      %smem_size_51 = cute_nvgpu.arch.get_dyn_smem_size() : i32 loc(#loc69)
      %c704_i32 = arith.constant 704 : i32 loc(#loc3)
      %14 = arith.cmpi sge, %smem_size_51, %c704_i32 : i32 loc(#loc61)
      cf.assert %14, "Allocation failed: shared memory allocation exceeds available memory set in kernel launch. Allocated bytes: 704 bytes. Please reduce the allocation or set a larger smem size in kernel launch." loc(#loc69)
      %int_tuple_52 = cute.make_int_tuple() : () -> !cute.int_tuple<"112"> loc(#loc59)
      %ptr_53 = cute.add_offset(%ptr_50, %int_tuple_52) : (!cute.ptr<i8, smem, align<64>>, !cute.int_tuple<"112">) -> !cute.ptr<i8, smem, align<16>> loc(#loc59)
      %smem_size_54 = cute_nvgpu.arch.get_dyn_smem_size() : i32 loc(#loc70)
      %c816_i32 = arith.constant 816 : i32 loc(#loc3)
      %15 = arith.cmpi sge, %smem_size_54, %c816_i32 : i32 loc(#loc61)
      cf.assert %15, "Allocation failed: shared memory allocation exceeds available memory set in kernel launch. Allocated bytes: 816 bytes. Please reduce the allocation or set a larger smem size in kernel launch." loc(#loc70)
      %iter_55 = cute.recast_iter(%ptr_50) : !cute.ptr<i8, smem, align<64>> to !cute.ptr<i64, smem, align<64>> loc(#loc70)
      %shape = cute.make_shape() : () -> !cute.shape<"(16,2)"> loc(#loc71)
      %lay_56 = cute.make_layout(%shape) : !cute.layout<"(16,2):(1,16)"> loc(#loc71)
      %coord = cute.make_coord() : () -> !cute.coord<"0"> loc(#loc72)
      %idx = cute.crd2idx(%coord, %lay_56) : (!cute.coord<"0">, !cute.layout<"(16,2):(1,16)">) -> !cute.int_tuple<"0"> loc(#loc72)
      %e0_57 = cute.get_leaves(%idx) : !cute.int_tuple<"0"> loc(#loc72)
      %cosz = cute.cosize(%lay_56) : (!cute.layout<"(16,2):(1,16)">) -> !cute.int_tuple<"32"> loc(#loc72)
      %e0_58 = cute.get_leaves(%cosz) : !cute.int_tuple<"32"> loc(#loc72)
      %16 = cute.ptrtoint(%ptr_53) : !cute.ptr<i8, smem, align<16>> to i32 loc(#loc62)
      %c32_i32 = arith.constant 32 : i32 loc(#loc3)
      %17 = arith.addi %16, %c32_i32 : i32 loc(#loc63)
      %18 = arith.subi %17, %c1_i32 : i32 loc(#loc63)
      %c-32_i32 = arith.constant -32 : i32 loc(#loc3)
      %19 = arith.andi %18, %c-32_i32 : i32 loc(#loc63)
      %20 = arith.extsi %19 : i32 to i64 loc(#loc3)
      %iv_59 = cute.assume(%20) : (i64) -> !cute.i64<divby 32> loc(#loc62)
      %21 = cute.inttoptr(%iv_59) : !cute.i64<divby 32> to !cute.ptr<i8, smem, align<32>> loc(#loc62)
      %int_tuple_60 = cute.make_int_tuple() : () -> !cute.int_tuple<"128"> loc(#loc59)
      %ptr_61 = cute.add_offset(%21, %int_tuple_60) : (!cute.ptr<i8, smem, align<32>>, !cute.int_tuple<"128">) -> !cute.ptr<i8, smem, align<32>> loc(#loc59)
      %smem_size_62 = cute_nvgpu.arch.get_dyn_smem_size() : i32 loc(#loc72)
      %c960_i32 = arith.constant 960 : i32 loc(#loc3)
      %22 = arith.cmpi sge, %smem_size_62, %c960_i32 : i32 loc(#loc61)
      cf.assert %22, "Allocation failed: shared memory allocation exceeds available memory set in kernel launch. Allocated bytes: 960 bytes. Please reduce the allocation or set a larger smem size in kernel launch." loc(#loc72)
      %iter_63 = cute.recast_iter(%21) : !cute.ptr<i8, smem, align<32>> to !cute.ptr<f32, smem, align<32>> loc(#loc72)
      %view = cute.make_view(%iter_63, %lay_56) : !memref_smem_f32_ loc(#loc72)
      %iter_64 = cute.get_iter(%view) : !memref_smem_f32_ loc(#loc73)
      %iter_65 = cute.recast_iter(%ptr_24) : !cute.ptr<i8, smem, align<128>> to !cute.ptr<f32, smem, align<128>> loc(#loc74)
      %lay_66 = cute.get_layout(%view) : !memref_smem_f32_ loc(#loc54)
      %23 = cute.get_shape(%lay_66) : (!cute.layout<"(16,2):(1,16)">) -> !cute.shape<"(16,2)"> loc(#loc55)
      %e0_67, %e1_68 = cute.get_leaves(%23) : !cute.shape<"(16,2)"> loc(#loc55)
      %24 = cute.get_stride(%lay_66) : (!cute.layout<"(16,2):(1,16)">) -> !cute.stride<"(1,16)"> loc(#loc56)
      %e0_69, %e1_70 = cute.get_leaves(%24) : !cute.stride<"(1,16)"> loc(#loc56)
      %shape_71 = cute.make_shape() : () -> !cute.shape<"(8,4)"> loc(#loc75)
      %lay_72 = cute.make_layout(%shape_71) : !cute.layout<"(8,4):(1,8)"> loc(#loc75)
      %iter_73 = cute.recast_iter(%ptr_24) : !cute.ptr<i8, smem, align<128>> to !cute.ptr<f32, smem, align<128>> loc(#loc76)
      %view_74 = cute.make_view(%iter_73, %lay_72) : !memref_smem_f32_1 loc(#loc77)
      %iter_75 = cute.get_iter(%view_74) : !memref_smem_f32_1 loc(#loc73)
      %sz = cute.size(%view_74) : (!memref_smem_f32_1) -> !cute.int_tuple<"32"> loc(#loc78)
      %e0_76 = cute.get_leaves(%sz) : !cute.int_tuple<"32"> loc(#loc78)
      %lay_77 = cute.get_layout(%view_74) : !memref_smem_f32_1 loc(#loc79)
      %25 = cute.get_shape(%lay_77) : (!cute.layout<"(8,4):(1,8)">) -> !cute.shape<"(8,4)"> loc(#loc79)
      %e0_78, %e1_79 = cute.get_leaves(%25) : !cute.shape<"(8,4)"> loc(#loc79)
      %int_tuple_80 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,4)"> loc(#loc78)
      %res = cute.tuple.product(%int_tuple_80) : (!cute.int_tuple<"(8,4)">) -> !cute.int_tuple<"32"> loc(#loc78)
      %e0_81 = cute.get_leaves(%res) : !cute.int_tuple<"32"> loc(#loc78)
      %cst = arith.constant 5.000000e-01 : f32 loc(#loc78)
      %26 = vector.splat %cst : vector<32xf32> loc(#loc78)
      %int_tuple_82 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,4)"> loc(#loc78)
      %sz_83 = cute.size(%int_tuple_82) : (!cute.int_tuple<"(8,4)">) -> !cute.int_tuple<"32"> loc(#loc78)
      %e0_84 = cute.get_leaves(%sz_83) : !cute.int_tuple<"32"> loc(#loc78)
      %int_tuple_85 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,4)"> loc(#loc78)
      %sz_86 = cute.size(%int_tuple_85) : (!cute.int_tuple<"(8,4)">) -> !cute.int_tuple<"32"> loc(#loc78)
      %e0_87 = cute.get_leaves(%sz_86) : !cute.int_tuple<"32"> loc(#loc78)
      cute.memref.store_vec %26, %view_74, row_major : !memref_smem_f32_1 loc(#loc78)
      cute.print("cute.struct.MemRange: {}\0A", %view_74) : !memref_smem_f32_1 loc(#loc80)
      %27 = cute.memref.load_vec %view_74, row_major : !memref_smem_f32_1 loc(#loc81)
      %lay_88 = cute.get_layout(%arg0) : !memref_gmem_f32_ loc(#loc79)
      %28 = cute.get_shape(%lay_88) : (!cute.layout<"(8,4):(4,1)">) -> !cute.shape<"(8,4)"> loc(#loc79)
      %e0_89, %e1_90 = cute.get_leaves(%28) : !cute.shape<"(8,4)"> loc(#loc79)
      %int_tuple_91 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,4)"> loc(#loc82)
      %sz_92 = cute.size(%int_tuple_91) : (!cute.int_tuple<"(8,4)">) -> !cute.int_tuple<"32"> loc(#loc82)
      %e0_93 = cute.get_leaves(%sz_92) : !cute.int_tuple<"32"> loc(#loc82)
      %int_tuple_94 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,4)"> loc(#loc82)
      %sz_95 = cute.size(%int_tuple_94) : (!cute.int_tuple<"(8,4)">) -> !cute.int_tuple<"32"> loc(#loc82)
      %e0_96 = cute.get_leaves(%sz_95) : !cute.int_tuple<"32"> loc(#loc82)
      cute.memref.store_vec %27, %arg0, row_major : !memref_gmem_f32_ loc(#loc82)
      %shape_97 = cute.make_shape() : () -> !cute.shape<"(8,2)"> loc(#loc83)
      %lay_98 = cute.make_layout(%shape_97) : !cute.layout<"(8,2):(1,8)"> loc(#loc83)
      %iter_99 = cute.recast_iter(%ptr_21) : !cute.ptr<i8, smem, align<128>> to !cute.ptr<f32, smem, align<128>> loc(#loc84)
      %view_100 = cute.make_view(%iter_99, %lay_98) : !memref_smem_f32_2 loc(#loc85)
      %iter_101 = cute.get_iter(%view_100) : !memref_smem_f32_2 loc(#loc73)
      %sz_102 = cute.size(%view_100) : (!memref_smem_f32_2) -> !cute.int_tuple<"16"> loc(#loc86)
      %e0_103 = cute.get_leaves(%sz_102) : !cute.int_tuple<"16"> loc(#loc86)
      %lay_104 = cute.get_layout(%view_100) : !memref_smem_f32_2 loc(#loc79)
      %29 = cute.get_shape(%lay_104) : (!cute.layout<"(8,2):(1,8)">) -> !cute.shape<"(8,2)"> loc(#loc79)
      %e0_105, %e1_106 = cute.get_leaves(%29) : !cute.shape<"(8,2)"> loc(#loc79)
      %int_tuple_107 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,2)"> loc(#loc86)
      %res_108 = cute.tuple.product(%int_tuple_107) : (!cute.int_tuple<"(8,2)">) -> !cute.int_tuple<"16"> loc(#loc86)
      %e0_109 = cute.get_leaves(%res_108) : !cute.int_tuple<"16"> loc(#loc86)
      %cst_110 = arith.constant 1.000000e+00 : f32 loc(#loc86)
      %30 = vector.splat %cst_110 : vector<16xf32> loc(#loc86)
      %int_tuple_111 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,2)"> loc(#loc86)
      %sz_112 = cute.size(%int_tuple_111) : (!cute.int_tuple<"(8,2)">) -> !cute.int_tuple<"16"> loc(#loc86)
      %e0_113 = cute.get_leaves(%sz_112) : !cute.int_tuple<"16"> loc(#loc86)
      %int_tuple_114 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,2)"> loc(#loc86)
      %sz_115 = cute.size(%int_tuple_114) : (!cute.int_tuple<"(8,2)">) -> !cute.int_tuple<"16"> loc(#loc86)
      %e0_116 = cute.get_leaves(%sz_115) : !cute.int_tuple<"16"> loc(#loc86)
      cute.memref.store_vec %30, %view_100, row_major : !memref_smem_f32_2 loc(#loc86)
      cute.print("block of memory: {}\0A", %view_100) : !memref_smem_f32_2 loc(#loc87)
      %31 = cute.memref.load_vec %view_100, row_major : !memref_smem_f32_2 loc(#loc88)
      %lay_117 = cute.get_layout(%arg1) : !memref_gmem_f32_1 loc(#loc79)
      %32 = cute.get_shape(%lay_117) : (!cute.layout<"(8,2):(2,1)">) -> !cute.shape<"(8,2)"> loc(#loc79)
      %e0_118, %e1_119 = cute.get_leaves(%32) : !cute.shape<"(8,2)"> loc(#loc79)
      %int_tuple_120 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,2)"> loc(#loc89)
      %sz_121 = cute.size(%int_tuple_120) : (!cute.int_tuple<"(8,2)">) -> !cute.int_tuple<"16"> loc(#loc89)
      %e0_122 = cute.get_leaves(%sz_121) : !cute.int_tuple<"16"> loc(#loc89)
      %int_tuple_123 = cute.make_int_tuple() : () -> !cute.int_tuple<"(8,2)"> loc(#loc89)
      %sz_124 = cute.size(%int_tuple_123) : (!cute.int_tuple<"(8,2)">) -> !cute.int_tuple<"16"> loc(#loc89)
      %e0_125 = cute.get_leaves(%sz_124) : !cute.int_tuple<"16"> loc(#loc89)
      cute.memref.store_vec %31, %arg1, row_major : !memref_gmem_f32_1 loc(#loc89)
      %sz_126 = cute.size(%view) : (!memref_smem_f32_) -> !cute.int_tuple<"32"> loc(#loc90)
      %e0_127 = cute.get_leaves(%sz_126) : !cute.int_tuple<"32"> loc(#loc90)
      %lay_128 = cute.get_layout(%view) : !memref_smem_f32_ loc(#loc79)
      %33 = cute.get_shape(%lay_128) : (!cute.layout<"(16,2):(1,16)">) -> !cute.shape<"(16,2)"> loc(#loc79)
      %e0_129, %e1_130 = cute.get_leaves(%33) : !cute.shape<"(16,2)"> loc(#loc79)
      %int_tuple_131 = cute.make_int_tuple() : () -> !cute.int_tuple<"(16,2)"> loc(#loc90)
      %res_132 = cute.tuple.product(%int_tuple_131) : (!cute.int_tuple<"(16,2)">) -> !cute.int_tuple<"32"> loc(#loc90)
      %e0_133 = cute.get_leaves(%res_132) : !cute.int_tuple<"32"> loc(#loc90)
      %cst_134 = arith.constant 2.000000e+00 : f32 loc(#loc90)
      %34 = vector.splat %cst_134 : vector<32xf32> loc(#loc90)
      %int_tuple_135 = cute.make_int_tuple() : () -> !cute.int_tuple<"(16,2)"> loc(#loc90)
      %sz_136 = cute.size(%int_tuple_135) : (!cute.int_tuple<"(16,2)">) -> !cute.int_tuple<"32"> loc(#loc90)
      %e0_137 = cute.get_leaves(%sz_136) : !cute.int_tuple<"32"> loc(#loc90)
      %int_tuple_138 = cute.make_int_tuple() : () -> !cute.int_tuple<"(16,2)"> loc(#loc90)
      %sz_139 = cute.size(%int_tuple_138) : (!cute.int_tuple<"(16,2)">) -> !cute.int_tuple<"32"> loc(#loc90)
      %e0_140 = cute.get_leaves(%sz_139) : !cute.int_tuple<"32"> loc(#loc90)
      cute.memref.store_vec %34, %view, row_major : !memref_smem_f32_ loc(#loc90)
      cute.print("tensor in smem: {}\0A", %view) : !memref_smem_f32_ loc(#loc91)
      %35 = cute.memref.load_vec %view, row_major : !memref_smem_f32_ loc(#loc92)
      %lay_141 = cute.get_layout(%arg2) : !memref_gmem_f32_2 loc(#loc79)
      %36 = cute.get_shape(%lay_141) : (!cute.layout<"(16,2):(2,1)">) -> !cute.shape<"(16,2)"> loc(#loc79)
      %e0_142, %e1_143 = cute.get_leaves(%36) : !cute.shape<"(16,2)"> loc(#loc79)
      %int_tuple_144 = cute.make_int_tuple() : () -> !cute.int_tuple<"(16,2)"> loc(#loc93)
      %sz_145 = cute.size(%int_tuple_144) : (!cute.int_tuple<"(16,2)">) -> !cute.int_tuple<"32"> loc(#loc93)
      %e0_146 = cute.get_leaves(%sz_145) : !cute.int_tuple<"32"> loc(#loc93)
      %int_tuple_147 = cute.make_int_tuple() : () -> !cute.int_tuple<"(16,2)"> loc(#loc93)
      %sz_148 = cute.size(%int_tuple_147) : (!cute.int_tuple<"(16,2)">) -> !cute.int_tuple<"32"> loc(#loc93)
      %e0_149 = cute.get_leaves(%sz_148) : !cute.int_tuple<"32"> loc(#loc93)
      cute.memref.store_vec %35, %arg2, row_major : !memref_gmem_f32_2 loc(#loc93)
      return loc(#loc3)
    } loc(#loc51)
  } loc(#loc50)
  func.func @cutlass_host_05_Tensorgmemo8441_10_Tensorgmemo8221_20_Tensorgmemo16221(%arg0: !memref_gmem_f32_ loc(unknown), %arg1: !memref_gmem_f32_1 loc(unknown), %arg2: !memref_gmem_f32_2 loc(unknown)) attributes {llvm.emit_c_interface} {
    %iter = cute.get_iter(%arg0) : !memref_gmem_f32_ loc(#loc52)
    %iter_0 = cute.get_iter(%arg1) : !memref_gmem_f32_1 loc(#loc52)
    %iter_1 = cute.get_iter(%arg2) : !memref_gmem_f32_2 loc(#loc52)
    %iter_2 = cute.get_iter(%arg0) : !memref_gmem_f32_ loc(#loc95)
    %iter_3 = cute.get_iter(%arg1) : !memref_gmem_f32_1 loc(#loc95)
    %iter_4 = cute.get_iter(%arg2) : !memref_gmem_f32_2 loc(#loc95)
    %lay = cute.get_layout(%arg0) : !memref_gmem_f32_ loc(#loc54)
    %0 = cute.get_shape(%lay) : (!cute.layout<"(8,4):(4,1)">) -> !cute.shape<"(8,4)"> loc(#loc55)
    %e0, %e1 = cute.get_leaves(%0) : !cute.shape<"(8,4)"> loc(#loc55)
    %1 = cute.get_stride(%lay) : (!cute.layout<"(8,4):(4,1)">) -> !cute.stride<"(4,1)"> loc(#loc56)
    %e0_5, %e1_6 = cute.get_leaves(%1) : !cute.stride<"(4,1)"> loc(#loc56)
    %lay_7 = cute.get_layout(%arg1) : !memref_gmem_f32_1 loc(#loc54)
    %2 = cute.get_shape(%lay_7) : (!cute.layout<"(8,2):(2,1)">) -> !cute.shape<"(8,2)"> loc(#loc55)
    %e0_8, %e1_9 = cute.get_leaves(%2) : !cute.shape<"(8,2)"> loc(#loc55)
    %3 = cute.get_stride(%lay_7) : (!cute.layout<"(8,2):(2,1)">) -> !cute.stride<"(2,1)"> loc(#loc56)
    %e0_10, %e1_11 = cute.get_leaves(%3) : !cute.stride<"(2,1)"> loc(#loc56)
    %lay_12 = cute.get_layout(%arg2) : !memref_gmem_f32_2 loc(#loc54)
    %4 = cute.get_shape(%lay_12) : (!cute.layout<"(16,2):(2,1)">) -> !cute.shape<"(16,2)"> loc(#loc55)
    %e0_13, %e1_14 = cute.get_leaves(%4) : !cute.shape<"(16,2)"> loc(#loc55)
    %5 = cute.get_stride(%lay_12) : (!cute.layout<"(16,2):(2,1)">) -> !cute.stride<"(2,1)"> loc(#loc56)
    %e0_15, %e1_16 = cute.get_leaves(%5) : !cute.stride<"(2,1)"> loc(#loc56)
    %lay_17 = cute.get_layout(%arg0) : !memref_gmem_f32_ loc(#loc54)
    %6 = cute.get_shape(%lay_17) : (!cute.layout<"(8,4):(4,1)">) -> !cute.shape<"(8,4)"> loc(#loc55)
    %e0_18, %e1_19 = cute.get_leaves(%6) : !cute.shape<"(8,4)"> loc(#loc55)
    %7 = cute.get_stride(%lay_17) : (!cute.layout<"(8,4):(4,1)">) -> !cute.stride<"(4,1)"> loc(#loc56)
    %e0_20, %e1_21 = cute.get_leaves(%7) : !cute.stride<"(4,1)"> loc(#loc56)
    %lay_22 = cute.get_layout(%arg1) : !memref_gmem_f32_1 loc(#loc54)
    %8 = cute.get_shape(%lay_22) : (!cute.layout<"(8,2):(2,1)">) -> !cute.shape<"(8,2)"> loc(#loc55)
    %e0_23, %e1_24 = cute.get_leaves(%8) : !cute.shape<"(8,2)"> loc(#loc55)
    %9 = cute.get_stride(%lay_22) : (!cute.layout<"(8,2):(2,1)">) -> !cute.stride<"(2,1)"> loc(#loc56)
    %e0_25, %e1_26 = cute.get_leaves(%9) : !cute.stride<"(2,1)"> loc(#loc56)
    %lay_27 = cute.get_layout(%arg2) : !memref_gmem_f32_2 loc(#loc54)
    %10 = cute.get_shape(%lay_27) : (!cute.layout<"(16,2):(2,1)">) -> !cute.shape<"(16,2)"> loc(#loc55)
    %e0_28, %e1_29 = cute.get_leaves(%10) : !cute.shape<"(16,2)"> loc(#loc55)
    %11 = cute.get_stride(%lay_27) : (!cute.layout<"(16,2):(2,1)">) -> !cute.stride<"(2,1)"> loc(#loc56)
    %e0_30, %e1_31 = cute.get_leaves(%11) : !cute.stride<"(2,1)"> loc(#loc56)
    %c1 = arith.constant 1 : index loc(#loc3)
    %c960_i32 = arith.constant 960 : i32 loc(#loc3)
    gpu.launch_func  @kernels::@kernel_cutlass_kernel_05_tensorptrf32gmemo8441_10_tensorptrf32gmemo8221_20_tensorptrf32gmemo16221_0 blocks in (%c1, %c1, %c1) threads in (%c1, %c1, %c1)  dynamic_shared_memory_size %c960_i32 args(%arg0 : !memref_gmem_f32_, %arg1 : !memref_gmem_f32_1, %arg2 : !memref_gmem_f32_2) {use_pdl = false} loc(#loc51)
    return loc(#loc96)
  } loc(#loc94)
} loc(#loc49)
#loc = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1118:42)
#loc1 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1124:61)
#loc2 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":176:4)
#loc4 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":656:19)
#loc5 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":169:15)
#loc6 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":156:66)
#loc7 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":800:29)
#loc8 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":800:54)
#loc9 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":98:16)
#loc10 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/utils/smem_allocator.py":156:28)
#loc11 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/utils/smem_allocator.py":172:8)
#loc12 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":102:14)
#loc13 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/utils/smem_allocator.py":181:12)
#loc14 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/utils/smem_allocator.py":170:21)
#loc15 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/typing.py":846:18)
#loc16 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":111:21)
#loc17 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":4073:70)
#loc18 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":4070:37)
#loc19 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":4070:26)
#loc20 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":4076:30)
#loc21 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":116:22)
#loc22 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":121:20)
#loc23 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":127:13)
#loc24 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":128:21)
#loc25 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/_mlir/dialects/_cute_ops_gen.py":2415:11)
#loc26 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":3883:19)
#loc27 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":147:43)
#loc28 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":3903:18)
#loc29 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/core.py":3904:18)
#loc30 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":148:4)
#loc31 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/tensor.py":390:15)
#loc32 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":149:4)
#loc33 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":150:16)
#loc34 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":150:4)
#loc35 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":153:13)
#loc36 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":154:14)
#loc37 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":155:17)
#loc38 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":156:4)
#loc39 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":157:4)
#loc40 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":158:16)
#loc41 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":158:4)
#loc42 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":161:4)
#loc43 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":162:4)
#loc44 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":163:16)
#loc45 = loc("/home/jayce.su/notes/dsl/cutlass_with_notes/examples/python/CuTeDSL/ampere/smem_allocator.py":163:4)
#loc46 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1127:57)
#loc47 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/cute/runtime.py":358:15)
#loc48 = loc("/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/dsl.py":1138:46)
#loc49 = loc("module = ir.Module.create(loc=self.get_location(frame))"(#loc))
#loc50 = loc("self._build_gpu_module(gpu_module_attrs, loc=self.get_location(frame))"(#loc1))
#loc51 = loc("kernel(const_a, dst_a, const_b, dst_b, const_c, dst_c).launch("(#loc2))
#loc52 = loc("fop_args = list(fop.regions[0].blocks[0].arguments)"(#loc4))
#loc53 = loc("return _Tensor("(#loc5))
#loc54 = loc("return f\22tensor<{pretty_str(self.iterator)} o {pretty_str(self.layout)}>\22"(#loc6))
#loc55 = loc("return f\22{pretty_str(self.shape)}:{pretty_str(self.stride)}\22"(#loc7))
#loc56 = loc("return f\22{pretty_str(self.shape)}:{pretty_str(self.stride)}\22"(#loc8))
#loc57 = loc("allocator = cutlass.utils.SmemAllocator()"(#loc9))
#loc58 = loc("size_in_bytes = cute.ceil_div(size_or_type.width, 8)"(#loc10))
#loc59 = loc("self._base += size_in_bytes"(#loc11))
#loc60 = loc("int_ptr = allocator.allocate(cutlass.Int32)"(#loc12))
#loc61 = loc("self._allocated_bytes <= get_dyn_smem_size(loc=loc, ip=ip),"(#loc13))
#loc62 = loc("self._base = self._base.align(byte_alignment)"(#loc14))
#loc63 = loc("res_val = op(lhs_val, rhs_val)"(#loc15))
#loc64 = loc("struct_in_smem = allocator.allocate(SharedStorage)"(#loc16))
#loc65 = loc("new_obj = struct._MemRangeData(obj._dtype, obj._size, base + off)"(#loc17))
#loc66 = loc("new_obj = recast_ptr(base + off, dtype=obj)"(#loc18))
#loc67 = loc("new_obj = recast_ptr(base + off, dtype=obj)"(#loc19))
#loc68 = loc("new_obj = obj(base + off)"(#loc20))
#loc69 = loc("section_in_smem = allocator.allocate(64, byte_alignment=128)"(#loc21))
#loc70 = loc("array_in_smem = allocator.allocate_array(element_type=cutlass.Int64, num_elems=14)"(#loc22))
#loc71 = loc("layout = cute.make_layout((16, 2))"(#loc23))
#loc72 = loc("tensor_in_smem = allocator.allocate_tensor("(#loc24))
#loc73 = loc("return self.operation.results[0]"(#loc25))
#loc74 = loc("return recast_ptr(self._base, dtype=self._dtype)"(#loc26))
#loc75 = loc("a_tensor = struct_in_smem.a.get_tensor(cute.make_layout((8, 4)))"(#loc27))
#loc76 = loc("ptr = recast_ptr(self._base, swizzle, dtype=elem_type)"(#loc28))
#loc77 = loc("res = make_tensor(ptr, layout)"(#loc29))
#loc78 = loc("a_tensor.fill(const_a)"(#loc30))
#loc79 = loc("return self.layout.shape"(#loc31))
#loc80 = loc("cute.printf(\22cute.struct.MemRange: {}\22, a_tensor)"(#loc32))
#loc81 = loc("dst_a.store(a_tensor.load())"(#loc33))
#loc82 = loc("dst_a.store(a_tensor.load())"(#loc34))
#loc83 = loc("layout = cute.make_layout((8, 2))"(#loc35))
#loc84 = loc("sec_ptr = cute.recast_ptr(section_in_smem, dtype=cutlass.Float32)"(#loc36))
#loc85 = loc("sec_tensor = cute.make_tensor(sec_ptr, layout)"(#loc37))
#loc86 = loc("sec_tensor.fill(const_b)"(#loc38))
#loc87 = loc("cute.printf(\22block of memory: {}\22, sec_tensor)"(#loc39))
#loc88 = loc("dst_b.store(sec_tensor.load())"(#loc40))
#loc89 = loc("dst_b.store(sec_tensor.load())"(#loc41))
#loc90 = loc("tensor_in_smem.fill(const_c)"(#loc42))
#loc91 = loc("cute.printf(\22tensor in smem: {}\22, tensor_in_smem)"(#loc43))
#loc92 = loc("dst_c.store(tensor_in_smem.load())"(#loc44))
#loc93 = loc("dst_c.store(tensor_in_smem.load())"(#loc45))
#loc94 = loc("function_name, (func_types, []), loc=self.get_location(frame)"(#loc46))
#loc95 = loc("return CoreTensor(values[0].value, self._dtype)"(#loc47))
#loc96 = loc("func.ReturnOp([], loc=self.get_location(frame))"(#loc48))

